/**
 * Phase D.0 — Generate 7 deterministic ed25519 keypairs + sign canonical
 * test message with first 4 (slot 0 = main + 1, 2, 3). Outputs Move-source-
 * ready hex constants for bench_multi_sig_4of7.
 *
 * Determinism: keys derived from a fixed seed (`PHASE_D_BENCH_SEED`) so the
 * same constants are reproducible across machines. The signatures are
 * deterministic ed25519 (RFC 8032 § 5.1.6), so they're also reproducible.
 *
 * Run: cd mvp-backend/operator-services && npx tsx ../move/scripts/gen_bench_keys.ts
 * Pipe to: mvp-backend/move/bench/sources/bench_keys.move
 */

import { Ed25519PrivateKey } from '@aptos-labs/ts-sdk';
import { createHash } from 'node:crypto';

const SEED = 'PHASE_D_BENCH_SEED_4OF7_MULTI_SIG_DETERMINISTIC';
const MSG = Buffer.from('PHASE_D_BENCH_MULTI_SIG_CANONICAL_MSG_64_BYTES_FIXED_FOR_GAS', 'utf8');

function deriveSeed(index: number): Uint8Array {
  // Derive each operator's 32-byte private key from SEED + index.
  const h = createHash('sha256');
  h.update(SEED);
  h.update(Buffer.from([index]));
  return h.digest();
}

function hex(b: Uint8Array | Buffer): string {
  return Array.from(b).map((x) => x.toString(16).padStart(2, '0')).join('');
}

function moveBytes(b: Uint8Array | Buffer): string {
  return `x"${hex(b)}"`;
}

const pubkeys: string[] = [];
const sigs: string[] = ['', '', '', '', '', '', ''];

for (let i = 0; i < 7; i++) {
  const sk = new Ed25519PrivateKey(deriveSeed(i));
  const pk = sk.publicKey();
  pubkeys.push(hex(pk.toUint8Array()));

  if (i < 4) {
    // Slot 0..3 sign the canonical message. Main = slot 0.
    const sigHex = sk.sign(MSG).toString().replace(/^0x/, '');
    sigs[i] = sigHex;
  }
}

console.log(`// AUTO-GENERATED by mvp-backend/move/scripts/gen_bench_keys.ts`);
console.log(`// Re-run if SEED or MSG changes. Do NOT hand-edit.`);
console.log(``);
console.log(`module eunoma_bench::bench_keys {`);
console.log(`    public fun message_bytes(): vector<u8> {`);
console.log(`        ${moveBytes(MSG)}`);
console.log(`    }`);
console.log(``);
console.log(`    public fun pubkeys(): vector<vector<u8>> {`);
console.log(`        let v = std::vector::empty<vector<u8>>();`);
for (let i = 0; i < 7; i++) {
  console.log(`        std::vector::push_back(&mut v, ${moveBytes(Buffer.from(pubkeys[i], 'hex'))});`);
}
console.log(`        v`);
console.log(`    }`);
console.log(``);
console.log(`    /// 4-of-7 signatures: filled slots 0 (main), 1, 2, 3; empty 4-6.`);
console.log(`    public fun signatures_4of7(): vector<vector<u8>> {`);
console.log(`        let v = std::vector::empty<vector<u8>>();`);
for (let i = 0; i < 7; i++) {
  if (sigs[i] !== '') {
    console.log(`        std::vector::push_back(&mut v, ${moveBytes(Buffer.from(sigs[i], 'hex'))});`);
  } else {
    console.log(`        std::vector::push_back(&mut v, std::vector::empty<u8>());`);
  }
}
console.log(`        v`);
console.log(`    }`);
console.log(`}`);
