// Generate 7 random bearer tokens (32 bytes each, base64-url-encoded) and
// print as .env lines. Run once when setting up a new operator deployment;
// append output to .env.
//
//   npx tsx scripts/generate_bearer_tokens.ts >> ../.env
//
// One token for main (OPERATOR_BEARER_TOKEN) + 6 per-partner-slot
// (PARTNER_BEARER_TOKEN_SLOT_1..6).

import { randomBytes } from "node:crypto";

function gen(): string {
  return randomBytes(32).toString("base64url");
}

console.log(`# === Bearer tokens generated by generate_bearer_tokens.ts ===`);
console.log(`# Generated at ${new Date().toISOString()}`);
console.log(`# Each token is 32 random bytes, base64url encoded. Rotate per deployment.`);
console.log(``);
console.log(`OPERATOR_BEARER_TOKEN=${gen()}`);
for (let slot = 1; slot <= 6; slot++) {
  console.log(`PARTNER_BEARER_TOKEN_SLOT_${slot}=${gen()}`);
}
console.log(``);
console.log(`# === end ===`);
