// One-shot migration: reads legacy JSON secret files in scripts/ and prints
// .env-formatted lines to stdout. Run once after upgrading to Phase 4 W3:
//
//   npx tsx scripts/migrate_json_secrets_to_env.ts >> ../../.env
//
// Then verify the .env contents and delete the JSON files:
//
//   rm scripts/.vault-ek.json scripts/.recipient-ek.json scripts/.user-ek.json scripts/.operator-keys.json
//
// This script writes ONLY to stdout — it never modifies the JSON files or .env
// itself, so it is safe to run repeatedly.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function readHexField(filePath: string, field: string = "private_key_hex"): string | null {
  if (!fs.existsSync(filePath)) return null;
  const obj = JSON.parse(fs.readFileSync(filePath, "utf-8"));
  const v = obj[field];
  if (typeof v !== "string") {
    throw new Error(`${filePath}: missing field "${field}"`);
  }
  return v;
}

function emit(name: string, value: string | null, comment: string) {
  if (value === null) {
    console.log(`# ${name}: source file not found, skipped (${comment})`);
    return;
  }
  console.log(`# ${comment}`);
  console.log(`${name}=${value}`);
}

console.log("# === Generated by migrate_json_secrets_to_env.ts ===");
console.log(`# Generated at ${new Date().toISOString()}`);
console.log("");

emit(
  "VAULT_DECRYPTION_KEY_HEX",
  readHexField(path.join(__dirname, ".vault-ek.json")),
  "Vault TwistedEd25519 decryption key (32 bytes hex)",
);

emit(
  "RECIPIENT_ENCRYPTION_KEY_HEX",
  readHexField(path.join(__dirname, ".recipient-ek.json")),
  "Bridge-spare recipient TwistedEd25519 keypair private key (32 bytes hex)",
);

emit(
  "USER_ENCRYPTION_KEY_HEX",
  readHexField(path.join(__dirname, ".user-ek.json")),
  "Bridge-user TwistedEd25519 keypair private key (32 bytes hex) — test user; in prod each user holds their own",
);

const opKeysPath = path.join(__dirname, ".operator-keys.json");
if (fs.existsSync(opKeysPath)) {
  const raw = fs.readFileSync(opKeysPath, "utf-8");
  // Validate it parses + has 7 entries
  const parsed = JSON.parse(raw);
  if (!Array.isArray(parsed) || parsed.length !== 7) {
    throw new Error(`${opKeysPath}: expected array of 7 operator keys, got ${Array.isArray(parsed) ? parsed.length : typeof parsed}`);
  }
  const b64 = Buffer.from(raw, "utf-8").toString("base64");
  console.log("# 7-of-7 operator Ed25519 signing keys (base64-encoded JSON array of {slot, role, private_key, public_key, address})");
  console.log(`OPERATOR_KEYS_JSON_B64=${b64}`);
} else {
  console.log("# OPERATOR_KEYS_JSON_B64: .operator-keys.json not found, skipped");
}

console.log("");
console.log("# Hardcoded secrets being migrated from scripts/ source:");
console.log("# - Search for ADMIN_PRIV / RELAYER_PRIV literals if these are not already set in your .env");
console.log("# - testnet_init_operator_set.ts:21 + testnet_init_withdraw.ts:22 → ADMIN_PRIVATE_KEY_HEX");
console.log("# - testnet_batch_root_update.ts:160 → RELAYER_PRIVATE_KEY_HEX");
console.log("");
console.log("# === end ===");
