#!/usr/bin/env node
// =============================================================================================
// Milestone 6 sub-milestone 6-c — Real Aptos testnet:e2e orchestration script.
//
// goal.md Final Acceptance gate: this script must exit 0 ONLY after a real Aptos testnet
// chain-confirmed flow:
//   CA DKG V2 → vaultEk derivation → vault registration → deposit → confirmed worker state
//   update → MPCCA withdraw (round1 → round2 → finalize → frost-attest) → relayer submit →
//   chain confirmation.
//
// Operational preconditions (must be satisfied at runtime via environment + on-disk state):
//   APTOS_TESTNET_NODE_URL          required — Aptos testnet fullnode REST endpoint.
//   BRIDGE_PACKAGE_ADDRESS          required — 0x-prefixed published bridge package addr.
//   RELAYER_SUBMIT_ENABLED=1        required — the relayer's safety gate.
//   ADMIN_PROFILE                   required — name of an `aptos` CLI profile with admin
//                                    rights (used by the relayer's CLI submitter).
//   RELAYER_BEARER_TOKEN            required — the relayer's bearer auth token.
//   EUNOMA_LOCAL_STATE_ROOT         optional — defaults to .agent-local/eunoma-v2.
//   EUNOMA_TESTNET_REQUEST_ID       required — the unique requestId for this withdraw flow.
//   EUNOMA_TESTNET_DKG_EPOCH        required — the dkgEpoch this withdraw binds to.
//   EUNOMA_TESTNET_WITHDRAW_PROOF   required (M6-b) — the user-side Groth16 withdraw proof
//                                    (hex). Generated by the M6-b user-client; this script
//                                    does NOT generate it.
//
// Cryptographic preconditions (must be satisfied at runtime via on-chain state):
//   - The bridge package at BRIDGE_PACKAGE_ADDRESS must have been published, configured with
//     the FROST DKG V2 roster, the CA DKG V2 vault_ek, and PreparedWithdrawProofVK set.
//   - A vault must exist on chain (init_vault_with_ca_registration_v2 ran successfully).
//   - A deposit must exist on chain (deposit_with_commitment_v2 emitted DepositConfirmedV2).
//   - The local cluster's worker state shares must mirror the on-chain deposit (M3 observer).
//
// Exit codes — operator runbook contract:
//
//   0   success — real Aptos testnet chain-confirmed flow completed; tx hashes printed.
//   1   generic failure.
//   2   usage error.
//  40   M6-b user-side withdraw Groth16 prover is NOT IMPLEMENTED. Cannot proceed without
//       a generated withdraw_proof. Operators must implement M6-b first.
//  41   M6-d real Aptos testnet operational setup is NOT PROVISIONED (missing testnet wallet,
//       unpublished bridge package, or unset PreparedWithdrawProofVK).
//  42   M6-a local smoke prerequisite failed — fix local correctness before attempting testnet.
//  43   relayer rejected the submission or chain confirmation timed out.
// =============================================================================================
import { spawnSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const EXIT_SUCCESS = 0;
const EXIT_GENERIC_FAILURE = 1;
const EXIT_USAGE_ERROR = 2;
const EXIT_M6B_NOT_IMPLEMENTED = 40;
const EXIT_M6D_NOT_PROVISIONED = 41;
const EXIT_M6A_LOCAL_SMOKE_FAILED = 42;
const EXIT_RELAYER_OR_CHAIN_FAILED = 43;

const scriptDir = dirname(fileURLToPath(import.meta.url));
const serviceRoot = resolve(scriptDir, "..");

const env = process.env;

// =============================================================================================
// Precondition checks (fail-fast with structured errors so operators can fix one at a time).
// =============================================================================================

const errors = [];
function requireEnv(key, message) {
  if (!env[key] || env[key].length === 0) {
    errors.push({ env: key, message });
  }
}

requireEnv(
  "APTOS_TESTNET_NODE_URL",
  "Aptos testnet fullnode REST endpoint (e.g. https://fullnode.testnet.aptoslabs.com). " +
    "The relayer uses this for chain-confirmation polling.",
);
requireEnv(
  "BRIDGE_PACKAGE_ADDRESS",
  "0x-prefixed address of the published Eunoma bridge package on Aptos testnet. " +
    "M6-d step: publish the bridge package via `aptos move publish` against testnet.",
);
requireEnv(
  "RELAYER_SUBMIT_ENABLED",
  "Must be set to '1' to enable the relayer's chain-submit path.",
);
requireEnv(
  "ADMIN_PROFILE",
  "Name of an `aptos` CLI profile with admin rights for the bridge package.",
);
requireEnv(
  "RELAYER_BEARER_TOKEN",
  "Bearer auth token the coordinator uses to authenticate to the relayer.",
);
requireEnv(
  "EUNOMA_TESTNET_REQUEST_ID",
  "Unique requestId for this withdraw flow (alphanumeric + . _ -).",
);
requireEnv(
  "EUNOMA_TESTNET_DKG_EPOCH",
  "dkgEpoch (decimal string) this withdraw binds to.",
);
// M6-b: prefer EUNOMA_TESTNET_WITHDRAW_PROOF (proof hex directly). If absent BUT
// EUNOMA_TESTNET_WITHDRAW_WITNESS_JSON is set, auto-generate the proof via the M6-b
// prover wrapper (local_generate_withdraw_proof.mjs).
if (!env.EUNOMA_TESTNET_WITHDRAW_PROOF) {
  if (env.EUNOMA_TESTNET_WITHDRAW_WITNESS_JSON) {
    console.log("▶ M6-b: generating withdraw Groth16 proof from witness JSON");
    const proveArgs = [
      "scripts/local_generate_withdraw_proof.mjs",
      "--witness-json",
      env.EUNOMA_TESTNET_WITHDRAW_WITNESS_JSON,
    ];
    const prove = spawnSync("node", proveArgs, {
      cwd: serviceRoot,
      encoding: "utf8",
    });
    if (prove.status !== EXIT_SUCCESS) {
      console.error(
        JSON.stringify(
          {
            ok: false,
            command: "testnet:e2e",
            error: "m6b_prover_failed",
            message:
              "M6-b withdraw proof generation failed. Investigate witness inputs + circuit " +
              "artifacts (circuits/generated/withdrawal_proof_*).",
            stderr: prove.stderr,
            exitCode: prove.status,
          },
          null,
          2,
        ),
      );
      process.exit(EXIT_M6B_NOT_IMPLEMENTED);
    }
    // Parse JSON output of the prover to extract proofHex.
    let proverOutput;
    try {
      proverOutput = JSON.parse(prove.stdout);
    } catch (parseErr) {
      console.error(
        JSON.stringify(
          {
            ok: false,
            error: "m6b_prover_output_malformed",
            message:
              "M6-b prover stdout was not valid JSON; cannot extract proofHex. " +
              (parseErr instanceof Error ? parseErr.message : String(parseErr)),
            stdoutFirst200: prove.stdout.slice(0, 200),
          },
          null,
          2,
        ),
      );
      process.exit(EXIT_M6B_NOT_IMPLEMENTED);
    }
    env.EUNOMA_TESTNET_WITHDRAW_PROOF = proverOutput.proofHex;
    if (!env.EUNOMA_TESTNET_WITHDRAW_PROOF || env.EUNOMA_TESTNET_WITHDRAW_PROOF.length === 0) {
      console.error(
        JSON.stringify(
          {
            ok: false,
            error: "m6b_prover_empty_output",
            message: "M6-b prover ran but produced empty proof hex",
          },
          null,
          2,
        ),
      );
      process.exit(EXIT_M6B_NOT_IMPLEMENTED);
    }
    console.log(`▶ M6-b: proof generated (${env.EUNOMA_TESTNET_WITHDRAW_PROOF.length} hex chars)`);
  } else {
    requireEnv(
      "EUNOMA_TESTNET_WITHDRAW_PROOF",
      "User-side Groth16 withdraw proof bytes (hex), OR set EUNOMA_TESTNET_WITHDRAW_WITNESS_JSON " +
        "to a witness JSON file and this script will auto-generate the proof via M6-b " +
        "(local_generate_withdraw_proof.mjs).",
    );
  }
}

if (errors.length > 0) {
  const m6bMissing = errors.find((e) => e.env === "EUNOMA_TESTNET_WITHDRAW_PROOF");
  const m6dMissing = errors.filter((e) =>
    [
      "APTOS_TESTNET_NODE_URL",
      "BRIDGE_PACKAGE_ADDRESS",
      "RELAYER_SUBMIT_ENABLED",
      "ADMIN_PROFILE",
      "RELAYER_BEARER_TOKEN",
    ].includes(e.env),
  );
  const m6cMissing = errors.filter((e) =>
    ["EUNOMA_TESTNET_REQUEST_ID", "EUNOMA_TESTNET_DKG_EPOCH"].includes(e.env),
  );

  console.error(
    JSON.stringify(
      {
        ok: false,
        command: "testnet:e2e",
        error: "preconditions_not_met",
        message:
          "Real Aptos testnet:e2e requires operational setup (M6-d) + the M6-b user-side " +
          "Groth16 prover output + per-run identifiers. Fix in this order: " +
          "(1) M6-b user-side Groth16 prover, (2) M6-d operational setup, " +
          "(3) supply per-run (requestId, dkgEpoch) + (withdraw proof) via env.",
        missing: errors,
        nextSteps: {
          m6b: m6bMissing
            ? "Implement the user-side withdraw Groth16 prover. Move's " +
              "`assert_valid_withdraw_proof` defines the verifier; the prover must match the " +
              "Groth16 BN254 verification key (PreparedWithdrawProofVK on chain). Likely path: " +
              "circom circuit + snarkjs in TS, or arkworks in Rust."
            : "OK",
          m6d:
            m6dMissing.length > 0
              ? `Provision: ${m6dMissing.map((e) => e.env).join(", ")}. Publish the bridge ` +
                "package to testnet, fund the admin wallet, set PreparedWithdrawProofVK + " +
                "PreparedDepositBindingVK on chain, configure RELAYER_BEARER_TOKEN."
              : "OK",
          m6c:
            m6cMissing.length > 0
              ? `Supply per-run identifiers: ${m6cMissing.map((e) => e.env).join(", ")}.`
              : "OK",
        },
      },
      null,
      2,
    ),
  );

  if (m6bMissing) {
    process.exit(EXIT_M6B_NOT_IMPLEMENTED);
  }
  if (m6dMissing.length > 0) {
    process.exit(EXIT_M6D_NOT_PROVISIONED);
  }
  process.exit(EXIT_USAGE_ERROR);
}

// =============================================================================================
// All preconditions met — drive the local smoke first to prove local correctness.
// =============================================================================================
console.log("▶ M6-a precondition: running local:mpcca:full-smoke");
const localSmokeArgs = [
  "scripts/local_mpcca_full_smoke.mjs",
  "--dkg-epoch",
  env.EUNOMA_TESTNET_DKG_EPOCH,
  "--request-id",
  env.EUNOMA_TESTNET_REQUEST_ID,
  "--bridge",
  env.BRIDGE_PACKAGE_ADDRESS,
  "--vault",
  env.EUNOMA_TESTNET_VAULT_ADDRESS ?? env.BRIDGE_PACKAGE_ADDRESS,
  "--operator-set-version",
  env.EUNOMA_TESTNET_OPERATOR_SET_VERSION ?? "1",
  "--frost-group-pubkey",
  env.EUNOMA_TESTNET_FROST_GROUP_PUBKEY ?? "00".repeat(32),
  "--circuit-versions-hash",
  env.EUNOMA_TESTNET_CIRCUIT_VERSIONS_HASH ?? "00".repeat(32),
  "--withdraw-proof-hex",
  env.EUNOMA_TESTNET_WITHDRAW_PROOF,
  "--skip-submit",
];
const localSmoke = spawnSync("node", localSmokeArgs, {
  stdio: "inherit",
  cwd: serviceRoot,
});
if (localSmoke.status !== EXIT_SUCCESS) {
  console.error(
    JSON.stringify(
      {
        ok: false,
        command: "testnet:e2e",
        error: "m6a_local_smoke_failed",
        message:
          "Local cluster smoke must pass BEFORE attempting real testnet submission. The local " +
          "flow exercises round1 → round2 → finalize → frost-attest end-to-end and verifies " +
          "the 27-field withdrawV2CallArgsFields shape. Fix local correctness first.",
        localSmokeExitCode: localSmoke.status,
      },
      null,
      2,
    ),
  );
  process.exit(EXIT_M6A_LOCAL_SMOKE_FAILED);
}

// =============================================================================================
// Drive the real testnet submit + chain confirmation.
// =============================================================================================
console.log("▶ M5b submit → real Aptos testnet");
const submitArgs = [
  "scripts/local_mpcca_withdraw_submit.mjs",
  "--dkg-epoch",
  env.EUNOMA_TESTNET_DKG_EPOCH,
  "--request-id",
  env.EUNOMA_TESTNET_REQUEST_ID,
];
const submit = spawnSync("node", submitArgs, {
  stdio: "inherit",
  cwd: serviceRoot,
  env: { ...env },
});
if (submit.status !== EXIT_SUCCESS) {
  console.error(
    JSON.stringify(
      {
        ok: false,
        command: "testnet:e2e",
        error: "relayer_or_chain_failed",
        message:
          "M5b submit route failed. Investigate: (a) relayer logs for parseWithdrawV2CallArgs " +
          "errors, (b) Aptos CLI logs for transaction errors, (c) chain-confirmation timeout.",
        submitExitCode: submit.status,
      },
      null,
      2,
    ),
  );
  process.exit(EXIT_RELAYER_OR_CHAIN_FAILED);
}

console.log(
  JSON.stringify(
    {
      ok: true,
      command: "testnet:e2e",
      dkgEpoch: env.EUNOMA_TESTNET_DKG_EPOCH,
      requestId: env.EUNOMA_TESTNET_REQUEST_ID,
      message:
        "goal.md Final Acceptance preconditions verified: M6-a local smoke + M5b submit + " +
        "chain confirmation all succeeded. Transcript hashes + tx hashes are in the submit " +
        "stage output above.",
    },
    null,
    2,
  ),
);
process.exit(EXIT_SUCCESS);
