// Gate 4a — Groth16 verifier round-trip test.
//
// Exercises the vendored `eunoma::groth16_bn254::verify_proof` against
// REAL Groth16 proofs generated by `circuits/deposit_binding.circom` + snarkjs.
// Fixtures live in `circuits/generated/move_fixtures/` and are regenerated by
// `node circuits/scripts/export_to_move.js` after every trusted-setup run.
//
// Byte format (per LOCAL_CONFIRMATION 8.7 + groth16_example test):
//   - VK / proof G1 points: uncompressed `FormatG1Uncompr` = 64 bytes (x_LE32 || y_LE32)
//   - VK / proof G2 points: uncompressed `FormatG2Uncompr` = 128 bytes
//                          (x_c0_LE32 || x_c1_LE32 || y_c0_LE32 || y_c1_LE32)
//   - Public inputs: `FormatFrLsb` = 32-byte LE
//
// Test strategy (3 cases):
//   1. positive — valid proof + valid public inputs => verify_proof == true
//   2. negative — valid proof + mutated commitment public input => verify_proof == false
//   3. negative — valid proof + mutated amount_tag public input => verify_proof == false
//
// Together these confirm:
//   (a) snarkjs <-> Move byte format round-trip works,
//   (b) snarkjs Groth16 proofs verify under Aptos's BN254 crypto_algebra natives,
//   (c) the Soundness property holds — mutating any one public input flips the
//       verify result to false (tests the same vector spread that snarkjs's
//       off-chain `groth16 verify` rejected in negative cases #1 and #2).
#[test_only]
module eunoma::groth16_verify_test {
    use std::option;
    use std::vector;

    use aptos_std::crypto_algebra::{Self as algebra, Element, enable_cryptography_algebra_natives};
    use aptos_std::bn254_algebra::{
        G1, G2, Gt, Fr,
        FormatG1Uncompr, FormatG2Uncompr, FormatFrLsb,
    };

    use eunoma::groth16_bn254;

    // ====================================================================
    //  VK constants (uncompressed bytes; auto-generated by export_to_move.js)
    // ====================================================================
    // Phase F W3 — regenerated for the 4-public-input circuit (chain_id+pool_id
    // baked as compile-time constants). VK delta + IC + proof bytes change with
    // every random contribution; the deterministic alpha/beta/gamma are stable.
    const VK_ALPHA_G1: vector<u8> = x"12c16beca06688485d74f21688948e77dedd9a4ad68b28b0eeb6293252e56826ae44c5727d76b62d79f2923c1c1bc5f58e778c4b03a3c58903cc6a1efc189109";
    const VK_BETA_G2:  vector<u8> = x"1ca4e89cceb6a9b7caabcd83980fcd69ef6df2b9d5f7b45d082e247807493c0ce21e5e7224aab40a95a0434fe84af514f9f81a5a4884abccad4fb8ec072a620d688459b1d0c167b809117b8cd25eb18b191f1a6f1406d4873ce49d06439c9e0fc8226b4a8f6578991eade15e60729cd6854e7160ae4b5d9640993c13184cb80b";
    const VK_GAMMA_G2: vector<u8> = x"edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19aa7dfa6601cce64c7bd3430c69e7d1e38f40cb8d8071ab4aeb6d8cdba55ec8125b9722d1dcdaac55f38eb37033314bbc95330c69ad999eec75f05f58d0890609";
    const VK_DELTA_G2: vector<u8> = x"28f894bd6fa2503e8fa6c95e3140cff9670b037e491a700c2125003072ef9a1d73fd1e0783d0dbdbcdeb9d55ae30465c9b20e1d265c2b0024a120c7a4d350e2ca0857cde259f1b035000a38624db47cf6bf95595ac65930367cd825393f6c801990632b426d639e4649494f499346fd3ff02f604ca030624d8d4147d44f92f1a";

    // IC[0..4] — vk_uvw_gamma_g1, length = 1 + 4 public inputs = 5 (snarkjs convention).
    const VK_IC_0: vector<u8> = x"f7c850638246b8203850b3ef63e55d5b35f6b7a385b523c3e775fd46b50b1e0feeb4adc4d85e2dce44b774e5ac64b1a82719f370965a1932c674527242849c0b";
    const VK_IC_1: vector<u8> = x"3590b33528bf6e17ce5015d6ac18d05bfeeb3c9e7f75675d3b64b558d5f8eb1cac1352465d8ee082ca0936150cfd34b3b137f0df824daba78b7b4a03aed46320";
    const VK_IC_2: vector<u8> = x"7e4325dff4f72c7d6aac99313818ff538b36cf774352ec4129290dddadfff825cfabf8e883b20675a48102aa212c568d6df0e7698949ae1fc9ba41c7ebacb72c";
    const VK_IC_3: vector<u8> = x"ababae53ea5208df20f73b178c92fa26cc0b0ec107e0853536eff74aac27372c654f8e5d7c464a38da6f7ea6e9949572844eab8b0b1de74a6ca5747ccfce341f";
    const VK_IC_4: vector<u8> = x"a0d4f0a41ebef3db789968a2fd37458c268849bf213f6c7eba2a72755b1f471d939ea92889637adebd1c00a5c5d5850643a3c8e401f78f1855d776ae6c1d5a01";

    // ====================================================================
    //  Valid proof (uncompressed bytes; Phase F W3 setup)
    // ====================================================================
    const PROOF_A: vector<u8> = x"035d4dc41c8787c35786ea004e5f8580d6ed9213fc7e1c290cdc8b2e5b6fd52de9f123547736b919f9081b5b3729e5fd44e4b235da428a93a8034c2d13470400";
    const PROOF_B: vector<u8> = x"ec2670b532abe71e375dd0314807cb5950f6934971ef104a7cc762a54a2c9f0ee6ed00c3665062b0eec4475ad69a4f53eab3fa210ab181109e45e6021b159a1b43b3492ddafec31e7bc59ee669b9431462ebfcb674ae267014055028cee5781570fa143731149f4c33091703301096d19a94e76a85fda0311cb1f171240b8409";
    const PROOF_C: vector<u8> = x"80fa277173e5d5f59ab1796471999d0e45476254451670dc3271369481cbea226b3ae6b9a745922740e95b3a66b8ef351ca90130d0519f6a739d66a890a18127";

    // ====================================================================
    //  Valid public inputs (Fr 32-byte LE, in snarkjs declaration order)
    // ====================================================================
    // [0] commitment, [1] amount_tag, [2] asset_id, [3] vault_addr_hash
    // (Phase F W3: chain_id + pool_id removed — circuit constants now.)
    const PUB_VALID_0: vector<u8> = x"942a57ac99245f1b86c292b9f835bc920a801db326a996b945c0bdbc48194613";
    const PUB_VALID_1: vector<u8> = x"02ba8cc71dad30d608b7a18018136fd36c83275b39c4a394de57060eeb368d2b";
    const PUB_VALID_2: vector<u8> = x"0700000000000000000000000000000000000000000000000000000000000000";
    const PUB_VALID_3: vector<u8> = x"edaffceedbeaedaffceedbeaedaffceedbeaedaffceedbeaedaffcee0befbe00";

    // Negative #1: same proof, mutated amount_tag (slot 1 high-byte tweaked).
    const PUB_NEG_AMT_TAG_0: vector<u8> = x"942a57ac99245f1b86c292b9f835bc920a801db326a996b945c0bdbc48194613";
    const PUB_NEG_AMT_TAG_1: vector<u8> = x"03ba8cc71dad30d608b7a18018136fd36c83275b39c4a394de57060eeb368d2b";
    const PUB_NEG_AMT_TAG_2: vector<u8> = x"0700000000000000000000000000000000000000000000000000000000000000";
    const PUB_NEG_AMT_TAG_3: vector<u8> = x"edaffceedbeaedaffceedbeaedaffceedbeaedaffceedbeaedaffcee0befbe00";

    // Negative #2: same proof, mutated commitment (slot 0 first byte tweaked).
    const PUB_NEG_CMT_0: vector<u8> = x"9b2a57ac99245f1b86c292b9f835bc920a801db326a996b945c0bdbc48194613";
    const PUB_NEG_CMT_1: vector<u8> = x"02ba8cc71dad30d608b7a18018136fd36c83275b39c4a394de57060eeb368d2b";
    const PUB_NEG_CMT_2: vector<u8> = x"0700000000000000000000000000000000000000000000000000000000000000";
    const PUB_NEG_CMT_3: vector<u8> = x"edaffceedbeaedaffceedbeaedaffceedbeaedaffceedbeaedaffcee0befbe00";

    // ====================================================================
    //  Helpers
    // ====================================================================

    // Deserialize a 64-byte uncompressed G1 point. Aborts if bytes don't decode
    // to a valid affine point on BN254 G1.
    fun de_g1(bytes: vector<u8>): Element<G1> {
        let opt = algebra::deserialize<G1, FormatG1Uncompr>(&bytes);
        option::extract(&mut opt)
    }

    // Deserialize a 128-byte uncompressed G2 point.
    fun de_g2(bytes: vector<u8>): Element<G2> {
        let opt = algebra::deserialize<G2, FormatG2Uncompr>(&bytes);
        option::extract(&mut opt)
    }

    // Deserialize a 32-byte LE Fr scalar.
    fun de_fr(bytes: vector<u8>): Element<Fr> {
        let opt = algebra::deserialize<Fr, FormatFrLsb>(&bytes);
        option::extract(&mut opt)
    }

    // Build the VK's vk_uvw_gamma_g1 vector (length 5 = 1 + 4 public inputs).
    // Phase F W3: 7 → 5 (chain_id + pool_id baked as circuit constants).
    fun load_ic(): vector<Element<G1>> {
        vector[
            de_g1(VK_IC_0),
            de_g1(VK_IC_1),
            de_g1(VK_IC_2),
            de_g1(VK_IC_3),
            de_g1(VK_IC_4),
        ]
    }

    fun load_public_valid(): vector<Element<Fr>> {
        vector[
            de_fr(PUB_VALID_0),
            de_fr(PUB_VALID_1),
            de_fr(PUB_VALID_2),
            de_fr(PUB_VALID_3),
        ]
    }

    fun load_public_neg_amount_tag(): vector<Element<Fr>> {
        vector[
            de_fr(PUB_NEG_AMT_TAG_0),
            de_fr(PUB_NEG_AMT_TAG_1),
            de_fr(PUB_NEG_AMT_TAG_2),
            de_fr(PUB_NEG_AMT_TAG_3),
        ]
    }

    fun load_public_neg_commitment(): vector<Element<Fr>> {
        vector[
            de_fr(PUB_NEG_CMT_0),
            de_fr(PUB_NEG_CMT_1),
            de_fr(PUB_NEG_CMT_2),
            de_fr(PUB_NEG_CMT_3),
        ]
    }

    // ====================================================================
    //  Tests
    // ====================================================================

    // Positive: valid (proof, VK, public inputs) => verify_proof returns true.
    // Pass criterion #5 of Gate 4a — REAL Groth16 round-trip Move <-> snarkjs.
    #[test(fx = @std)]
    fun verify_valid_proof(fx: signer) {
        enable_cryptography_algebra_natives(&fx);

        let vk_alpha = de_g1(VK_ALPHA_G1);
        let vk_beta  = de_g2(VK_BETA_G2);
        let vk_gamma = de_g2(VK_GAMMA_G2);
        let vk_delta = de_g2(VK_DELTA_G2);
        let vk_ic    = load_ic();

        let publics  = load_public_valid();

        let proof_a  = de_g1(PROOF_A);
        let proof_b  = de_g2(PROOF_B);
        let proof_c  = de_g1(PROOF_C);

        // Sanity-check IC length matches snarkjs convention (1 + n_public_inputs).
        assert!(vector::length(&vk_ic) == 1 + vector::length(&publics), 0);

        let ok = groth16_bn254::verify_proof<G1, G2, Gt, Fr>(
            &vk_alpha,
            &vk_beta,
            &vk_gamma,
            &vk_delta,
            &vk_ic,
            &publics,
            &proof_a,
            &proof_b,
            &proof_c,
        );
        assert!(ok, 1);
    }

    // Negative: valid proof, mutated amount_tag public input => verify_proof returns false.
    // Same proof bytes as positive case, but amount_tag's high-byte is tweaked
    // so the verifier's pairing equation no longer holds.
    #[test(fx = @std)]
    fun reject_proof_with_wrong_amount_tag(fx: signer) {
        enable_cryptography_algebra_natives(&fx);

        let vk_alpha = de_g1(VK_ALPHA_G1);
        let vk_beta  = de_g2(VK_BETA_G2);
        let vk_gamma = de_g2(VK_GAMMA_G2);
        let vk_delta = de_g2(VK_DELTA_G2);
        let vk_ic    = load_ic();

        let publics  = load_public_neg_amount_tag();

        let proof_a  = de_g1(PROOF_A);
        let proof_b  = de_g2(PROOF_B);
        let proof_c  = de_g1(PROOF_C);

        let ok = groth16_bn254::verify_proof<G1, G2, Gt, Fr>(
            &vk_alpha,
            &vk_beta,
            &vk_gamma,
            &vk_delta,
            &vk_ic,
            &publics,
            &proof_a,
            &proof_b,
            &proof_c,
        );
        assert!(!ok, 2);
    }

    // Negative: valid proof, mutated commitment public input => verify_proof returns false.
    #[test(fx = @std)]
    fun reject_proof_with_wrong_commitment(fx: signer) {
        enable_cryptography_algebra_natives(&fx);

        let vk_alpha = de_g1(VK_ALPHA_G1);
        let vk_beta  = de_g2(VK_BETA_G2);
        let vk_gamma = de_g2(VK_GAMMA_G2);
        let vk_delta = de_g2(VK_DELTA_G2);
        let vk_ic    = load_ic();

        let publics  = load_public_neg_commitment();

        let proof_a  = de_g1(PROOF_A);
        let proof_b  = de_g2(PROOF_B);
        let proof_c  = de_g1(PROOF_C);

        let ok = groth16_bn254::verify_proof<G1, G2, Gt, Fr>(
            &vk_alpha,
            &vk_beta,
            &vk_gamma,
            &vk_delta,
            &vk_ic,
            &publics,
            &proof_a,
            &proof_b,
            &proof_c,
        );
        assert!(!ok, 3);
    }
}
