//! Milestone 4a commit 3 — byte-for-byte parity tests for the single-party
//! Aptos CA `TransferV1` sigma proof reference port.
//!
//! These tests load the committed fixture from
//! `operator-services/deop-protocol/tests/fixtures/aptos_ca_transfer_v1_fixture.json`
//! (generated by the TS fixture script with a deterministic SHA-256 PRNG keyed
//! by `EUNOMA_APTOS_CA_TRANSFER_V1_FIXTURE_PRNG_SEED`) and assert that the
//! Rust prover output is byte-identical to the Aptos SDK output.

use std::{fs, path::PathBuf};

use curve25519_dalek::scalar::Scalar;
use curve25519_dalek::{
    constants::RISTRETTO_BASEPOINT_POINT, ristretto::RistrettoPoint, traits::Identity,
};
use eunoma_crypto_worker::transfer_sigma_reference::{
    bcs_fiat_shamir_inputs, bcs_serialize_transfer_session, build_statement, prng_next_scalar_list,
    prove_transfer_single_party, sigma_fiat_shamir_seed,
    threshold::{
        aggregate_threshold_sigma_commitments, aggregate_threshold_sigma_responses,
        compute_threshold_sigma_partial_commitment, compute_threshold_sigma_response_share,
        derive_dk_base_points, COMMITMENT_LEN, WITNESS_LEN,
    },
    verify_transfer_single_party, CounterPrng, DomainSeparator, SigmaProtocolProof,
    TransferStatementInputs, APTOS_FRAMEWORK_ADDRESS, PROTOCOL_ID, TYPE_NAME,
};
use serde::Deserialize;

const FIXTURE_REL_PATH: &str = "../deop-protocol/tests/fixtures/aptos_ca_transfer_v1_fixture.json";

const SDK_FILE_REF: &str = "@aptos-labs/confidential-asset/src/crypto/sigmaProtocolTransfer.ts";

// =============================================================================
// Fixture wire types
// =============================================================================

#[derive(Debug, Deserialize)]
struct Fixture {
    generator: GeneratorInfo,
    params: Params,
    witness: WitnessFixture,
    statement: StatementFixture,
    #[serde(rename = "plaintextChunks")]
    plaintext_chunks: PlaintextChunks,
    randomness: Randomness,
    ciphertexts: Ciphertexts,
    #[serde(rename = "sigmaProof")]
    sigma_proof: SigmaProofFixture,
    prng: PrngInfo,
}

#[derive(Debug, Deserialize)]
struct GeneratorInfo {
    #[serde(rename = "sigmaProtocolId")]
    sigma_protocol_id: String,
    #[serde(rename = "sigmaTypeName")]
    sigma_type_name: String,
    #[serde(rename = "prngSeed")]
    prng_seed: String,
}

#[derive(Debug, Deserialize)]
struct Params {
    ell: usize,
    n: usize,
    #[serde(rename = "chunkBits")]
    chunk_bits: usize,
    #[serde(rename = "hasAuditor")]
    has_auditor: bool,
    #[serde(rename = "numAuditors")]
    num_auditors: usize,
    amount: u64,
    #[serde(rename = "oldBalance")]
    old_balance: u64,
    #[serde(rename = "newBalance")]
    new_balance: u64,
}

#[derive(Debug, Deserialize)]
struct WitnessFixture {
    dk: String,
}

#[derive(Debug, Deserialize)]
struct StatementFixture {
    #[serde(rename = "senderAddress")]
    sender_address: String,
    #[serde(rename = "recipientAddress")]
    recipient_address: String,
    #[serde(rename = "tokenAddress")]
    token_address: String,
    #[serde(rename = "chainId")]
    chain_id: u8,
    #[serde(rename = "senderEk")]
    sender_ek: String,
    #[serde(rename = "recipientEk")]
    recipient_ek: String,
}

#[derive(Debug, Deserialize)]
struct PlaintextChunks {
    #[serde(rename = "newBalance")]
    new_balance: Vec<String>,
    #[serde(rename = "transferAmount")]
    transfer_amount: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct Randomness {
    // `oldBalance` blinding factors are present in the fixture for cross-
    // reference but the *sigma* witness only needs the new balance + transfer
    // amount randomness vectors. (Old-balance randomness only feeds the
    // ciphertexts that appear in the public statement, which we already pass
    // through verbatim.) We intentionally do NOT read this field here.
    #[serde(default, rename = "oldBalance")]
    _old_balance: Vec<String>,
    #[serde(rename = "transferAmount")]
    transfer_amount: Vec<String>,
    #[serde(rename = "newBalance")]
    new_balance: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct Ciphertexts {
    #[serde(rename = "oldBalanceC")]
    old_balance_c: Vec<String>,
    #[serde(rename = "oldBalanceD")]
    old_balance_d: Vec<String>,
    #[serde(rename = "newBalanceC")]
    new_balance_c: Vec<String>,
    #[serde(rename = "newBalanceD")]
    new_balance_d: Vec<String>,
    #[serde(rename = "amountC")]
    amount_c: Vec<String>,
    #[serde(rename = "amountDSender")]
    amount_d_sender: Vec<String>,
    #[serde(rename = "amountDRecipient")]
    amount_d_recipient: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct SigmaProofFixture {
    commitment: Vec<String>,
    response: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct PrngInfo {
    #[serde(rename = "bytesConsumedThroughSigmaProof")]
    bytes_consumed_through_sigma_proof: usize,
}

// =============================================================================
// Hex helpers
// =============================================================================

fn hex_decode(s: &str) -> Vec<u8> {
    let raw = s
        .strip_prefix("0x")
        .or_else(|| s.strip_prefix("0X"))
        .unwrap_or(s);
    let mut out = Vec::with_capacity(raw.len() / 2);
    for i in (0..raw.len()).step_by(2) {
        out.push(u8::from_str_radix(&raw[i..i + 2], 16).expect("hex byte"));
    }
    out
}

fn hex_32(s: &str) -> [u8; 32] {
    let bytes = hex_decode(s);
    assert_eq!(bytes.len(), 32, "expected 32 bytes");
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn load_fixture() -> Fixture {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(FIXTURE_REL_PATH);
    let bytes =
        fs::read(&path).unwrap_or_else(|err| panic!("read fixture at {}: {err}", path.display()));
    serde_json::from_slice(&bytes).expect("parse fixture json")
}

// =============================================================================
// Helpers for building the prover input from the fixture
// =============================================================================

/// Interpret a 32-byte LE-encoded scalar (the format the TS fixture stores
/// randomness in via `scalarBytesLE`, sigmaProtocolTransfer.ts witness).
fn scalar_from_le_hex(s: &str) -> Scalar {
    Scalar::from_bytes_mod_order(hex_32(s))
}

fn scalars_from_le_hex(items: &[String]) -> Vec<Scalar> {
    items.iter().map(|s| scalar_from_le_hex(s)).collect()
}

fn scalars_from_decimal(items: &[String]) -> Vec<Scalar> {
    items
        .iter()
        .map(|d| Scalar::from(u64::from_str_radix(d, 10).expect("decimal chunk")))
        .collect()
}

fn compress_list(items: &[String]) -> Vec<[u8; 32]> {
    items.iter().map(|h| hex_32(h)).collect()
}

fn build_dst(stmt: &StatementFixture, ell: usize, n: usize) -> DomainSeparator {
    let sender = hex_32(&stmt.sender_address);
    let recipient = hex_32(&stmt.recipient_address);
    let asset = hex_32(&stmt.token_address);
    let session =
        bcs_serialize_transfer_session(&sender, &recipient, &asset, ell as u64, n as u64, false, 0);
    DomainSeparator {
        contract_address: APTOS_FRAMEWORK_ADDRESS,
        chain_id: stmt.chain_id,
        protocol_id: PROTOCOL_ID.as_bytes().to_vec(),
        session_id: session,
    }
}

// =============================================================================
// Witness/alpha reconstruction
// =============================================================================

/// dk lives in the fixture as the raw 32-byte secret key (NOT mod-n reduced).
/// The TS prover does `bytesToNumberLE(dk.toUint8Array())` which is a *bigint*
/// without explicit reduction — but `Scalar` arithmetic on `from_bytes_mod_order`
/// would reduce. Since the fixture's dk has the top nibble cleared (< 2^252,
/// well below ℓ), the two are equivalent. We replicate the TS path via
/// `from_bytes_mod_order` to keep the comparison rigorous.
fn dk_scalar(dk_hex: &str) -> Scalar {
    Scalar::from_bytes_mod_order(hex_32(dk_hex))
}

/// Reconstruct the 25-scalar witness `[dk, new_a[8], new_r[8], v[4], r[4]]`.
fn build_witness(fix: &Fixture) -> Vec<Scalar> {
    let mut w = Vec::with_capacity(1 + 2 * fix.params.ell + 2 * fix.params.n);
    w.push(dk_scalar(&fix.witness.dk));
    w.extend(scalars_from_decimal(&fix.plaintext_chunks.new_balance));
    w.extend(scalars_from_le_hex(&fix.randomness.new_balance));
    w.extend(scalars_from_decimal(&fix.plaintext_chunks.transfer_amount));
    w.extend(scalars_from_le_hex(&fix.randomness.transfer_amount));
    w
}

/// Replay the PRNG to reach the same `alpha` vector the TS prover consumed.
///
/// Determinism contract (see `aptos_ca_transfer_parity.test.ts:60-75`):
///   1. ell scalars  → oldBalanceRandomness
///   2. n scalars    → transferAmountRandomness
///   3. ell scalars  → newBalanceRandomness
///   4. WASM init (range proof) consumes 32 bytes
///   5. WASM ChaCha12 stream consumes N bytes for range proof 1 + 2
///   6. k scalars    → sigma alpha          ← this is what we want
///
/// We replay steps 1-3 by drawing the same 8+4+8 scalars (and discarding
/// them — they only advance the PRNG cursor). Steps 4-5 happen at WASM-init
/// time and inside the Rust `bulletproof_reference` test; the sigma fixture's
/// alpha block sits *before* those WASM consumptions because `proveTransfer`
/// pulls all 25 alpha scalars from noble randomBytes BEFORE any WASM call —
/// see `sigmaProtocol.ts:267`.
///
/// Wait: looking again at the TS test, the order is:
///   * draw 20 randomness scalars (noble)
///   * call batchRangeProof(amount)  → WASM init pulls 32 bytes from getRandomValues
///   * call batchRangeProof(newBalance) → WASM is already initialized
///   * call proveTransfer(...) → ed25519GenListOfRandom(25) inside → 25 alpha scalars (noble)
///
/// So the alpha block is consumed *after* the WASM-init 32 bytes AND any WASM-
/// internal calls that may pull from getRandomValues after init. Per
/// `getrandom/src/js.rs`, only the *initial* OsRng-from-OS read pulls from
/// getRandomValues — subsequent randomness comes from the seeded ChaCha12 in
/// `thread_rng`. So between the 2 batchRangeProof calls and proveTransfer,
/// getRandomValues is hit ONLY at the very first batchRangeProof (32 bytes).
///
/// Thus the PRNG cursor before alpha = 20*32 + 32 = 672 bytes.
fn replay_alpha_via_prng(fix: &Fixture, k: usize) -> Vec<Scalar> {
    let mut prng = CounterPrng::new(&fix.generator.prng_seed);
    let _ = prng_next_scalar_list(&mut prng, fix.params.ell); // oldBalance randomness
    let _ = prng_next_scalar_list(&mut prng, fix.params.n); // transferAmount randomness
    let _ = prng_next_scalar_list(&mut prng, fix.params.ell); // newBalance randomness
    prng.skip(32); // WASM thread_rng init (consumed at first batchRangeProof call)
    prng_next_scalar_list(&mut prng, k)
}

// =============================================================================
// Tests
// =============================================================================

#[test]
fn fixture_constants_match_aptos_sdk() {
    let fix = load_fixture();
    assert_eq!(fix.generator.sigma_protocol_id, PROTOCOL_ID);
    assert_eq!(
        fix.generator.sigma_type_name,
        "0x1::sigma_protocol_transfer::Transfer"
    );
    assert_eq!(fix.params.ell, 8);
    assert_eq!(fix.params.n, 4);
    assert_eq!(fix.params.chunk_bits, 16);
    assert!(!fix.params.has_auditor);
    assert_eq!(fix.params.num_auditors, 0);
    assert_eq!(fix.params.amount, 100);
    assert_eq!(fix.params.old_balance, 1000);
    assert_eq!(fix.params.new_balance, 900);
    assert_eq!(fix.sigma_proof.commitment.len(), 30);
    assert_eq!(fix.sigma_proof.response.len(), 25);
    // Sanity: PRNG advanced past the alpha-25 block.
    assert!(fix.prng.bytes_consumed_through_sigma_proof >= 25 * 32);
    // We DO NOT assert ell*32 / n*32 layout here — TS rejection-sampling can
    // consume extra bytes (it's empirically rare but possible). The byte-parity
    // test below is the real check.
}

#[test]
fn aptos_ca_transfer_sigma_byte_parity_with_aptos_sdk() {
    let fix = load_fixture();
    let ell = fix.params.ell;
    let n = fix.params.n;

    let inputs = TransferStatementInputs {
        sender_ek: hex_32(&fix.statement.sender_ek),
        recipient_ek: hex_32(&fix.statement.recipient_ek),
        old_balance_c: compress_list(&fix.ciphertexts.old_balance_c),
        old_balance_d: compress_list(&fix.ciphertexts.old_balance_d),
        new_balance_c: compress_list(&fix.ciphertexts.new_balance_c),
        new_balance_d: compress_list(&fix.ciphertexts.new_balance_d),
        transfer_amount_c: compress_list(&fix.ciphertexts.amount_c),
        transfer_amount_d_sender: compress_list(&fix.ciphertexts.amount_d_sender),
        transfer_amount_d_recipient: compress_list(&fix.ciphertexts.amount_d_recipient),
    };
    let statement = build_statement(&inputs).expect("build statement");
    let dst = build_dst(&fix.statement, ell, n);
    let witness = build_witness(&fix);
    let alpha = replay_alpha_via_prng(&fix, witness.len());

    assert_eq!(witness.len(), 25, "{}", SDK_FILE_REF);
    assert_eq!(alpha.len(), 25);

    let proof = prove_transfer_single_party(&witness, &statement, &alpha, &dst, ell, n, false, 0)
        .expect("prove");
    assert_eq!(
        proof.commitment.len(),
        30,
        "transfer sigma shape: 30 commitment points per {SDK_FILE_REF}:319"
    );
    assert_eq!(
        proof.response.len(),
        25,
        "transfer sigma shape: 25 response scalars per {SDK_FILE_REF}:319"
    );

    // Byte parity — commitments
    for (i, expected_hex) in fix.sigma_proof.commitment.iter().enumerate() {
        let expected = hex_32(expected_hex);
        assert_eq!(
            hex_encode(&proof.commitment[i]),
            hex_encode(&expected),
            "sigma commitment[{i}] byte mismatch ({SDK_FILE_REF}:282)"
        );
    }
    // Byte parity — responses
    for (i, expected_hex) in fix.sigma_proof.response.iter().enumerate() {
        let expected = hex_32(expected_hex);
        assert_eq!(
            hex_encode(&proof.response[i]),
            hex_encode(&expected),
            "sigma response[{i}] byte mismatch ({SDK_FILE_REF}:283)"
        );
    }
}

#[test]
fn verify_transfer_byte_parity() {
    let fix = load_fixture();
    let ell = fix.params.ell;
    let n = fix.params.n;

    let inputs = TransferStatementInputs {
        sender_ek: hex_32(&fix.statement.sender_ek),
        recipient_ek: hex_32(&fix.statement.recipient_ek),
        old_balance_c: compress_list(&fix.ciphertexts.old_balance_c),
        old_balance_d: compress_list(&fix.ciphertexts.old_balance_d),
        new_balance_c: compress_list(&fix.ciphertexts.new_balance_c),
        new_balance_d: compress_list(&fix.ciphertexts.new_balance_d),
        transfer_amount_c: compress_list(&fix.ciphertexts.amount_c),
        transfer_amount_d_sender: compress_list(&fix.ciphertexts.amount_d_sender),
        transfer_amount_d_recipient: compress_list(&fix.ciphertexts.amount_d_recipient),
    };
    let statement = build_statement(&inputs).expect("build statement");
    let dst = build_dst(&fix.statement, ell, n);

    let proof = SigmaProtocolProof {
        commitment: fix
            .sigma_proof
            .commitment
            .iter()
            .map(|h| hex_32(h))
            .collect(),
        response: fix.sigma_proof.response.iter().map(|h| hex_32(h)).collect(),
    };
    assert!(
        verify_transfer_single_party(&proof, &statement, &dst, ell, n, false, 0)
            .expect("verify ok"),
        "Aptos SDK sigma proof must verify under our reference port (sigmaProtocol.ts:307-351)"
    );
}

#[test]
fn tampered_sender_address_changes_fiat_shamir() {
    let fix = load_fixture();
    let ell = fix.params.ell;
    let n = fix.params.n;

    let inputs = TransferStatementInputs {
        sender_ek: hex_32(&fix.statement.sender_ek),
        recipient_ek: hex_32(&fix.statement.recipient_ek),
        old_balance_c: compress_list(&fix.ciphertexts.old_balance_c),
        old_balance_d: compress_list(&fix.ciphertexts.old_balance_d),
        new_balance_c: compress_list(&fix.ciphertexts.new_balance_c),
        new_balance_d: compress_list(&fix.ciphertexts.new_balance_d),
        transfer_amount_c: compress_list(&fix.ciphertexts.amount_c),
        transfer_amount_d_sender: compress_list(&fix.ciphertexts.amount_d_sender),
        transfer_amount_d_recipient: compress_list(&fix.ciphertexts.amount_d_recipient),
    };
    let statement = build_statement(&inputs).expect("build statement");

    // Same alpha + witness, but flip 1 byte of sender address → different DST
    // → different challenge e → response shifts.
    let mut bad_sender = hex_32(&fix.statement.sender_address);
    bad_sender[0] ^= 0x01;
    let recipient = hex_32(&fix.statement.recipient_address);
    let asset = hex_32(&fix.statement.token_address);
    let bad_session = bcs_serialize_transfer_session(
        &bad_sender,
        &recipient,
        &asset,
        ell as u64,
        n as u64,
        false,
        0,
    );
    let bad_dst = DomainSeparator {
        contract_address: APTOS_FRAMEWORK_ADDRESS,
        chain_id: fix.statement.chain_id,
        protocol_id: PROTOCOL_ID.as_bytes().to_vec(),
        session_id: bad_session,
    };

    let witness = build_witness(&fix);
    let alpha = replay_alpha_via_prng(&fix, witness.len());

    let good_dst = build_dst(&fix.statement, ell, n);
    let good_proof =
        prove_transfer_single_party(&witness, &statement, &alpha, &good_dst, ell, n, false, 0)
            .expect("prove good");
    let bad_proof =
        prove_transfer_single_party(&witness, &statement, &alpha, &bad_dst, ell, n, false, 0)
            .expect("prove bad");

    // Commitments are functions of psi(alpha) and the statement points — both
    // unchanged. So they must still match.
    assert_eq!(good_proof.commitment, bad_proof.commitment);
    // Responses depend on e, which is now different. response[0] (the dk
    // response) is the canonical place to check.
    assert_ne!(
        good_proof.response[0], bad_proof.response[0],
        "flipping sender address must change Fiat-Shamir e and thus response[0]"
    );
}

#[test]
fn auditor_branches_unsupported() {
    let fix = load_fixture();
    let ell = fix.params.ell;
    let n = fix.params.n;

    let inputs = TransferStatementInputs {
        sender_ek: hex_32(&fix.statement.sender_ek),
        recipient_ek: hex_32(&fix.statement.recipient_ek),
        old_balance_c: compress_list(&fix.ciphertexts.old_balance_c),
        old_balance_d: compress_list(&fix.ciphertexts.old_balance_d),
        new_balance_c: compress_list(&fix.ciphertexts.new_balance_c),
        new_balance_d: compress_list(&fix.ciphertexts.new_balance_d),
        transfer_amount_c: compress_list(&fix.ciphertexts.amount_c),
        transfer_amount_d_sender: compress_list(&fix.ciphertexts.amount_d_sender),
        transfer_amount_d_recipient: compress_list(&fix.ciphertexts.amount_d_recipient),
    };
    let statement = build_statement(&inputs).expect("build statement");
    let dst = build_dst(&fix.statement, ell, n);
    let witness = build_witness(&fix);
    let alpha = replay_alpha_via_prng(&fix, witness.len());

    let err = prove_transfer_single_party(&witness, &statement, &alpha, &dst, ell, n, true, 0)
        .expect_err("hasEffective=true must be rejected");
    assert!(format!("{err:?}").contains("auditor"));

    let err = prove_transfer_single_party(&witness, &statement, &alpha, &dst, ell, n, false, 1)
        .expect_err("numVolun=1 must be rejected");
    assert!(format!("{err:?}").contains("auditor"));
}

// =============================================================================
// Milestone 4c — threshold Σ-protocol primitive byte-parity tests
//
// These exercise the load-bearing invariant of the threshold construction:
// additive sharing of (witness, alpha) across 5 parties + per-party
// commitment/response computation + aggregation MUST byte-match the
// single-party M4a fixture. The challenge `e` is computed by single-party
// Fiat-Shamir on the *aggregated* commitment vector (which equals the M4a A).
// =============================================================================

const NUM_PARTIES: usize = 5;

/// Deterministic test scalar from a label. Same construction as the
/// twisted_elgamal threshold tests, but with a distinct domain to avoid
/// label collisions across the two test files.
fn det_scalar(label: &[u8]) -> Scalar {
    use sha2::{Digest, Sha512};
    let mut h = Sha512::new();
    h.update(b"EUNOMA_M4C_TRANSFER_SIGMA_TEST_DET_SCALAR_V1");
    h.update((label.len() as u64).to_le_bytes());
    h.update(label);
    let mut wide = [0u8; 64];
    wide.copy_from_slice(&h.finalize());
    Scalar::from_bytes_mod_order_wide(&wide)
}

/// Convert a 25-element scalar slice to a `[Scalar; 25]` array for the
/// threshold API.
fn to_25(v: &[Scalar]) -> [Scalar; WITNESS_LEN] {
    let mut out = [Scalar::ZERO; WITNESS_LEN];
    assert_eq!(v.len(), WITNESS_LEN, "expected 25-scalar vector");
    out.copy_from_slice(v);
    out
}

/// Split a 25-scalar vector into 5 additive shares, each a `[Scalar; 25]`,
/// whose per-index sum equals the input. Four pseudorandom shares plus a
/// balancing fifth share. Deterministic per `domain_label`.
fn split_vector_into_five_additive_shares(
    v: &[Scalar; WITNESS_LEN],
    domain_label: &[u8],
) -> [[Scalar; WITNESS_LEN]; NUM_PARTIES] {
    let mut shares = [[Scalar::ZERO; WITNESS_LEN]; NUM_PARTIES];
    for i in 0..WITNESS_LEN {
        let mut sum_pseudorandom = Scalar::ZERO;
        for j in 0..(NUM_PARTIES - 1) {
            let label = format!("party/{j}/index/{i}").into_bytes();
            let s = det_scalar(&[domain_label, b"/", label.as_slice()].concat());
            shares[j][i] = s;
            sum_pseudorandom += s;
        }
        // Balancing share so Σ shares[j][i] == v[i].
        shares[NUM_PARTIES - 1][i] = v[i] - sum_pseudorandom;
    }
    shares
}

/// Common test setup: load fixture, build statement + DST + witness + alpha.
fn build_threshold_test_context() -> (
    Fixture,
    eunoma_crypto_worker::transfer_sigma_reference::Statement,
    DomainSeparator,
    [Scalar; WITNESS_LEN],
    [Scalar; WITNESS_LEN],
) {
    let fix = load_fixture();
    let ell = fix.params.ell;
    let n = fix.params.n;

    let inputs = TransferStatementInputs {
        sender_ek: hex_32(&fix.statement.sender_ek),
        recipient_ek: hex_32(&fix.statement.recipient_ek),
        old_balance_c: compress_list(&fix.ciphertexts.old_balance_c),
        old_balance_d: compress_list(&fix.ciphertexts.old_balance_d),
        new_balance_c: compress_list(&fix.ciphertexts.new_balance_c),
        new_balance_d: compress_list(&fix.ciphertexts.new_balance_d),
        transfer_amount_c: compress_list(&fix.ciphertexts.amount_c),
        transfer_amount_d_sender: compress_list(&fix.ciphertexts.amount_d_sender),
        transfer_amount_d_recipient: compress_list(&fix.ciphertexts.amount_d_recipient),
    };
    let statement = build_statement(&inputs).expect("build statement");
    let dst = build_dst(&fix.statement, ell, n);
    let witness_vec = build_witness(&fix);
    let alpha_vec = replay_alpha_via_prng(&fix, witness_vec.len());
    let witness = to_25(&witness_vec);
    let alpha = to_25(&alpha_vec);
    (fix, statement, dst, witness, alpha)
}

/// Run the threshold-prove pipeline end-to-end given pre-computed shares.
///
/// Returns `(aggregated_commitment_bytes_30, aggregated_response_bytes_25,
/// challenge_e)`.
fn run_threshold_pipeline(
    statement: &eunoma_crypto_worker::transfer_sigma_reference::Statement,
    dst: &DomainSeparator,
    alpha_shares: &[[Scalar; WITNESS_LEN]; NUM_PARTIES],
    witness_shares: &[[Scalar; WITNESS_LEN]; NUM_PARTIES],
    ell: usize,
    n: usize,
) -> (Vec<[u8; 32]>, Vec<[u8; 32]>, Scalar) {
    // Round 1: each party computes A_share_j = psi(α_share_j).
    let mut commitments = Vec::with_capacity(NUM_PARTIES);
    for j in 0..NUM_PARTIES {
        let a_share = compute_threshold_sigma_partial_commitment(
            &alpha_shares[j],
            statement,
            ell,
            n,
            false,
            0,
        )
        .expect("compute partial commitment");
        commitments.push(a_share);
    }

    // Aggregate to get A = Σ A_share.
    let a_agg = aggregate_threshold_sigma_commitments(&commitments);
    let a_compressed: Vec<[u8; 32]> = a_agg.iter().map(|p| p.compress().to_bytes()).collect();
    assert_eq!(a_compressed.len(), COMMITMENT_LEN);

    // Round 2: compute Fiat-Shamir challenge `e` from the AGGREGATED A.
    let bcs = bcs_fiat_shamir_inputs(
        dst,
        TYPE_NAME,
        WITNESS_LEN as u64,
        &statement.compressed_points,
        &statement.scalars,
        &a_compressed,
    );
    let (e, _beta) = sigma_fiat_shamir_seed(&bcs);

    // Round 3: each party computes s_share_j = α_share_j + e · w_share_j.
    let mut responses = Vec::with_capacity(NUM_PARTIES);
    for j in 0..NUM_PARTIES {
        let s_share =
            compute_threshold_sigma_response_share(&alpha_shares[j], &witness_shares[j], &e);
        responses.push(s_share);
    }

    // Aggregate to get s = Σ s_share.
    let s_agg = aggregate_threshold_sigma_responses(&responses);
    let s_bytes: Vec<[u8; 32]> = s_agg.iter().map(|s| s.to_bytes()).collect();
    assert_eq!(s_bytes.len(), WITNESS_LEN);

    (a_compressed, s_bytes, e)
}

#[test]
fn threshold_sigma_byte_parity_with_m4a_fixture_response() {
    let (fix, statement, dst, witness, alpha) = build_threshold_test_context();
    let ell = fix.params.ell;
    let n = fix.params.n;

    // Split α and w into 5 additive shares each. Distinct domain labels so
    // the α-split and w-split shares are independent (no accidental coupling).
    let alpha_shares =
        split_vector_into_five_additive_shares(&alpha, b"M4C_TRANSFER_SIGMA_ALPHA_SPLIT_V1");
    let witness_shares =
        split_vector_into_five_additive_shares(&witness, b"M4C_TRANSFER_SIGMA_WITNESS_SPLIT_V1");

    // Sanity: shares actually sum to α and w (catch a wrong split before
    // attributing a byte mismatch to the threshold math).
    for i in 0..WITNESS_LEN {
        let sum_alpha: Scalar = (0..NUM_PARTIES).map(|j| alpha_shares[j][i]).sum();
        let sum_w: Scalar = (0..NUM_PARTIES).map(|j| witness_shares[j][i]).sum();
        assert_eq!(sum_alpha, alpha[i], "alpha share split[{i}] sum mismatch");
        assert_eq!(sum_w, witness[i], "witness share split[{i}] sum mismatch");
    }

    let (a_compressed, s_bytes, _e) =
        run_threshold_pipeline(&statement, &dst, &alpha_shares, &witness_shares, ell, n);

    // LOAD-BEARING BYTE PARITY: 30 commitments + 25 responses must byte-match
    // the M4a fixture.
    assert_eq!(a_compressed.len(), 30);
    assert_eq!(s_bytes.len(), 25);
    for (i, expected_hex) in fix.sigma_proof.commitment.iter().enumerate() {
        let expected = hex_32(expected_hex);
        assert_eq!(
            hex_encode(&a_compressed[i]),
            hex_encode(&expected),
            "threshold sigma commitment[{i}] disagrees with M4a fixture ({SDK_FILE_REF}:282)"
        );
    }
    for (i, expected_hex) in fix.sigma_proof.response.iter().enumerate() {
        let expected = hex_32(expected_hex);
        assert_eq!(
            hex_encode(&s_bytes[i]),
            hex_encode(&expected),
            "threshold sigma response[{i}] disagrees with M4a fixture ({SDK_FILE_REF}:283)"
        );
    }
}

#[test]
fn threshold_sigma_zero_shares_collapse_to_single_party() {
    let (fix, statement, dst, witness, alpha) = build_threshold_test_context();
    let ell = fix.params.ell;
    let n = fix.params.n;

    // Special case: parties 0..4 contribute zero shares; party 4 holds full
    // witness + alpha. By linearity, the aggregate must equal the single-party
    // output (and thus byte-match the fixture).
    let mut alpha_shares = [[Scalar::ZERO; WITNESS_LEN]; NUM_PARTIES];
    let mut witness_shares = [[Scalar::ZERO; WITNESS_LEN]; NUM_PARTIES];
    alpha_shares[NUM_PARTIES - 1] = alpha;
    witness_shares[NUM_PARTIES - 1] = witness;

    let (a_compressed, s_bytes, _e) =
        run_threshold_pipeline(&statement, &dst, &alpha_shares, &witness_shares, ell, n);

    for (i, expected_hex) in fix.sigma_proof.commitment.iter().enumerate() {
        let expected = hex_32(expected_hex);
        assert_eq!(
            hex_encode(&a_compressed[i]),
            hex_encode(&expected),
            "zero-shares commitment[{i}] must collapse to single-party fixture"
        );
    }
    for (i, expected_hex) in fix.sigma_proof.response.iter().enumerate() {
        let expected = hex_32(expected_hex);
        assert_eq!(
            hex_encode(&s_bytes[i]),
            hex_encode(&expected),
            "zero-shares response[{i}] must collapse to single-party fixture"
        );
    }
}

#[test]
fn threshold_sigma_arbitrary_share_decomposition_byte_parity() {
    let (fix, statement, dst, witness, alpha) = build_threshold_test_context();
    let ell = fix.params.ell;
    let n = fix.params.n;

    // A DIFFERENT random additive split (distinct domain labels) — the
    // byte-parity invariant should be agnostic to the share decomposition.
    let alpha_shares = split_vector_into_five_additive_shares(
        &alpha,
        b"M4C_TRANSFER_SIGMA_ARBITRARY_ALPHA_SPLIT_V1",
    );
    let witness_shares = split_vector_into_five_additive_shares(
        &witness,
        b"M4C_TRANSFER_SIGMA_ARBITRARY_WITNESS_SPLIT_V1",
    );

    // Verify the shares are different from the first test's splits (sanity:
    // distinct decomposition → exercises the same invariant from a different
    // starting point).
    let other_alpha_shares =
        split_vector_into_five_additive_shares(&alpha, b"M4C_TRANSFER_SIGMA_ALPHA_SPLIT_V1");
    assert_ne!(
        alpha_shares[0][0], other_alpha_shares[0][0],
        "two distinct domain labels must give distinct first-party first-index alpha shares"
    );

    let (a_compressed, s_bytes, _e) =
        run_threshold_pipeline(&statement, &dst, &alpha_shares, &witness_shares, ell, n);

    for (i, expected_hex) in fix.sigma_proof.commitment.iter().enumerate() {
        let expected = hex_32(expected_hex);
        assert_eq!(
            hex_encode(&a_compressed[i]),
            hex_encode(&expected),
            "arbitrary-split commitment[{i}] disagrees with M4a fixture"
        );
    }
    for (i, expected_hex) in fix.sigma_proof.response.iter().enumerate() {
        let expected = hex_32(expected_hex);
        assert_eq!(
            hex_encode(&s_bytes[i]),
            hex_encode(&expected),
            "arbitrary-split response[{i}] disagrees with M4a fixture"
        );
    }
}

// =============================================================================
// M4 Commit 1 — derive_dk_base_points: programmatic BASE_DK_SET inspection
// =============================================================================
//
// `derive_dk_base_points` runs `psi_transfer` with the unit witness vector
// `α = [1, 0, 0, ..., 0]`. By linearity of psi in α (PSI LINEARITY CHECK in
// `transfer_sigma_reference.rs`), the output isolates the witness[0]-dependent
// contributions at every position; non-identity outputs identify the indices
// where dk contributes, and the output values are exactly the public base
// points multiplying dk at those positions.
//
// For the Aptos CA `TransferV1` (ell=8, n=4, no auditor), the two dk-bearing
// positions are:
//
//   index  0 (sigmaProtocolTransfer.ts:316 / lib.rs psi_transfer step 1):
//          base = ek_sid (= statement.points[IDX_EK_SID])
//
//   index 17 (sigmaProtocolTransfer.ts:343 / lib.rs psi_transfer step 4
//             balance equation, dk-component):
//          base = Σ_i (b_pow_ell[i] · old_R[i])
//                 = Σ_i (2^(16·i) · statement.old_balance_d[i])
//
// These tests use the committed M4a fixture so they DOUBLY assert (a) that
// the indices match the analytical answer and (b) that the recovered base
// points match the canonical bases as built from the same fixture data.

fn b_pow_ell(count: usize) -> Vec<Scalar> {
    let b = Scalar::from(1u64 << 16);
    let mut out = Vec::with_capacity(count);
    out.push(Scalar::ONE);
    for i in 1..count {
        out.push(out[i - 1] * b);
    }
    out
}

#[test]
fn derive_dk_base_points_indices_are_zero_and_seventeen() {
    let (_fix, statement, _dst, _witness, _alpha) = build_threshold_test_context();
    let pts = derive_dk_base_points(&statement, 8, 4, false, 0).expect("derive");
    let indices: Vec<usize> = pts.iter().map(|p| p.index).collect();
    assert_eq!(
        indices,
        vec![0_usize, 17_usize],
        "BASE_DK_SET indices MUST be exactly {{0, 17}} for the Aptos CA TransferV1 shape"
    );
    // No identity bases sneak through.
    let identity = RistrettoPoint::identity();
    for p in &pts {
        assert_ne!(p.base, identity, "dk base at index {} is identity", p.index);
    }
}

#[test]
fn derive_dk_base_points_bases_match_canonical_ek_sid_and_old_r_combined() {
    let (fix, statement, _dst, _witness, _alpha) = build_threshold_test_context();
    let pts = derive_dk_base_points(&statement, 8, 4, false, 0).expect("derive");
    assert_eq!(pts.len(), 2);

    // Position 0 → base == ek_sid.
    let expected_ek_sid_bytes = hex_32(&fix.statement.sender_ek);
    let actual_idx0 = pts.iter().find(|p| p.index == 0).expect("index 0 missing");
    let actual_idx0_bytes = actual_idx0.base.compress().to_bytes();
    assert_eq!(
        hex_encode(&actual_idx0_bytes),
        hex_encode(&expected_ek_sid_bytes),
        "index 0 base point MUST equal the sender ek_sid (= statement.points[IDX_EK_SID])"
    );

    // Position 17 → base == Σ_i (b_pow_ell[i] · old_R[i])
    // where old_R[i] = statement.old_balance_d[i].
    let ell = fix.params.ell;
    let powers = b_pow_ell(ell);
    let mut expected = RistrettoPoint::identity();
    for (i, comp_hex) in fix.ciphertexts.old_balance_d.iter().enumerate() {
        let comp = hex_32(comp_hex);
        let point = curve25519_dalek::ristretto::CompressedRistretto(comp)
            .decompress()
            .expect("decompress old_balance_d");
        expected += point * powers[i];
    }
    // Sanity: the user-supplied (compressed) old_balance_d byte order parses
    // to the same point set the statement holds; we double-check this by
    // referencing statement.points[12..20] (start_idx_old_r(ell) = 12).
    for i in 0..ell {
        let stmt_p = statement.points[12 + i];
        let parsed = curve25519_dalek::ristretto::CompressedRistretto(hex_32(
            &fix.ciphertexts.old_balance_d[i],
        ))
        .decompress()
        .expect("decompress");
        assert_eq!(
            stmt_p, parsed,
            "statement.points[12+{i}] disagrees with old_balance_d[{i}]"
        );
    }
    let actual_idx17 = pts
        .iter()
        .find(|p| p.index == 17)
        .expect("index 17 missing");
    let actual_idx17_bytes = actual_idx17.base.compress().to_bytes();
    assert_eq!(
        hex_encode(&actual_idx17_bytes),
        hex_encode(&expected.compress().to_bytes()),
        "index 17 base point MUST equal Σ_i (b_pow_ell[i] · old_balance_d[i])"
    );

    // Tertiary defense-in-depth: scaling each derived base by a fresh α gives
    // the dk-only psi output for α_unit = [α, 0, ..., 0]. Run the threshold
    // partial-commitment API on this exact witness and assert the same.
    let alpha_scalar = Scalar::from(0x5a5a_5a5a_u64);
    let mut alpha_unit = [Scalar::ZERO; WITNESS_LEN];
    alpha_unit[0] = alpha_scalar;
    let a_partial =
        compute_threshold_sigma_partial_commitment(&alpha_unit, &statement, 8, 4, false, 0)
            .expect("compute partial commitment for alpha-unit");
    let identity = RistrettoPoint::identity();
    for (idx, point) in a_partial.iter().enumerate() {
        if idx == 0 || idx == 17 {
            let expected = pts.iter().find(|p| p.index == idx).expect("base").base * alpha_scalar;
            assert_eq!(
                *point, expected,
                "psi(α_unit)[{idx}] != α · base — derive_dk_base_points base is wrong"
            );
        } else {
            assert_eq!(
                *point, identity,
                "psi(α_unit) leaked a non-identity at index {idx} — dk leaks outside BASE_DK_SET"
            );
        }
    }
    // Suppress unused-import warning for `RISTRETTO_BASEPOINT_POINT`; the import
    // exists so future tests can reference G without a fresh use statement.
    let _ = RISTRETTO_BASEPOINT_POINT;
}
