//! Plan task **M10-g** — rust reference verifier parity test for the
//! σ-position-17 (TransferV1 balance equation) multi-deposit hard-stop.
//!
//! M10-a's JS-side test
//! (`operator-services/scripts/__tests__/sigma_position_17_parity.test.mjs`)
//! empirically confirmed that σ position 17 verifies for synthetic
//! `deposit_count ∈ {1, 2, 8}` aggregates with a truthful balance witness,
//! and that hard-coding `new_a = [0; ELL]` (replicating the M9 bug) makes
//! position 17 fail while every other position still verifies.
//!
//! This rust integration test cross-validates that diagnosis by feeding the
//! same fixtures through the rust reference verifier
//! (`crypto_worker_rust::src::transfer_sigma_reference.rs`). If the two
//! implementations agree on the per-position fail mask byte-for-byte, the
//! diagnosis is double-locked.
//!
//! ## Fixture lineage
//!
//! Each fixture in `tests/fixtures/sigma_17/*.json` is generated by
//! `operator-services/scripts/gen_sigma_position_17_rust_fixtures.mjs` under a
//! deterministic SHA-256-counter PRNG (installed BEFORE the SDK loads).
//! Re-running the generator must produce byte-identical fixtures (the
//! generator itself asserts that via a re-read + diff check; set
//! `EUNOMA_REGENERATE_FIXTURES=1` to intentionally rotate).
//!
//! Each fixture captures:
//!   * Full Σ-protocol statement (sender/recipient/token addresses, sender +
//!     recipient ek, every ciphertext for old/new balance and transfer
//!     amount).
//!   * The SDK-produced σ-proof bytes (`commitment[30]` + `response[25]`).
//!   * The JS reference verifier's ground-truth `failsByPosition[30]` from
//!     `scripts/sigma_reference_verifier.mjs` — recorded inside the same JSON
//!     so the rust assertion is `rust_fails_by_position == js_fails_by_position`
//!     element-wise. If those vectors disagree, one of the two reference
//!     verifiers has drifted and the parity diagnosis is REFUTED.
//!
//! ## Test matrix (mirrors the M10-a JS test)
//!
//! | # | name                                | total | xfer | new_a override | expected fails |
//! |---|-------------------------------------|-------|------|----------------|----------------|
//! | 1 | `1_deposit_happy_path`              | 100   | 100  | none           | []             |
//! | 2 | `2_deposit_happy_path`              | 250   | 100  | none           | []             |
//! | 3 | `8_deposit_happy_path`              | 828   | 100  | none           | []             |
//! | 4 | `8_deposit_zero_new_a_regression`   | 828   | 100  | [0;8]          | [17]           |
//!
//! ## What the assertions encode
//!
//!   * 3 happy-path fixtures (1/2/8 deposits): every one of the 30 positions
//!     verifies in BOTH JS and rust. The aggregate `verify_transfer_single_party`
//!     boolean is `true`. σ position 17 specifically is asserted to verify
//!     (the M10 diagnostic target).
//!   * 1 regression fixture (8 deposits, new_a=0): position 17 fails in BOTH
//!     JS and rust. The aggregate boolean is `false`. The other 29 positions
//!     verify. This is the strict regression guard: if a future SDK change
//!     causes any of those other 29 positions to fail, or position 17 to
//!     verify with new_a=0, the diagnosis must be revisited.
//!
//! No modification of `transfer_sigma_reference.rs`'s production verifier is
//! involved: the test invokes the `verify_transfer_per_position_for_parity_tests`
//! entry point (a minimal test-only public function added next to the
//! production `verify_transfer_single_party`), and additionally calls the
//! production `verify_transfer_single_party` to confirm the per-position
//! result is consistent with the aggregate boolean.

use std::{
    fs,
    path::{Path, PathBuf},
};

use eunoma_crypto_worker::transfer_sigma_reference::{
    bcs_serialize_transfer_session, build_statement, verify_transfer_per_position_for_parity_tests,
    verify_transfer_single_party, DomainSeparator, SigmaProtocolProof, TransferStatementInputs,
    APTOS_FRAMEWORK_ADDRESS, PROTOCOL_ID,
};
use serde::Deserialize;

// =============================================================================
// Fixture wire types
// =============================================================================

#[derive(Debug, Deserialize)]
struct Fixture {
    meta: Meta,
    statement: StatementFixture,
    #[serde(rename = "sigmaProof")]
    sigma_proof: SigmaProofFixture,
    debug: DebugFixture,
}

#[derive(Debug, Deserialize)]
struct Meta {
    name: String,
    description: String,
    ell: usize,
    n: usize,
    #[serde(rename = "chainId")]
    chain_id: u8,
    #[serde(rename = "hasEffectiveAuditor")]
    has_effective_auditor: bool,
    #[serde(rename = "numVolunAuditors")]
    num_volun_auditors: usize,
    #[serde(rename = "totalOctas")]
    total_octas: String,
    #[serde(rename = "transferOctas")]
    transfer_octas: String,
    #[serde(rename = "jsReferenceVerifier")]
    js_reference_verifier: JsRef,
}

#[derive(Debug, Deserialize)]
struct JsRef {
    #[serde(rename = "allPass")]
    all_pass: bool,
    #[serde(rename = "failsByPosition")]
    fails_by_position: Vec<u8>,
    #[serde(rename = "challengeHex")]
    #[allow(dead_code)]
    challenge_hex: String,
}

#[derive(Debug, Deserialize)]
struct StatementFixture {
    #[serde(rename = "senderAddressHex")]
    sender_address_hex: String,
    #[serde(rename = "recipientAddressHex")]
    recipient_address_hex: String,
    #[serde(rename = "tokenAddressHex")]
    token_address_hex: String,
    #[serde(rename = "senderEkHex")]
    sender_ek_hex: String,
    #[serde(rename = "recipientEkHex")]
    recipient_ek_hex: String,
    #[serde(rename = "oldBalanceC")]
    old_balance_c: Vec<String>,
    #[serde(rename = "oldBalanceD")]
    old_balance_d: Vec<String>,
    #[serde(rename = "newBalanceC")]
    new_balance_c: Vec<String>,
    #[serde(rename = "newBalanceD")]
    new_balance_d: Vec<String>,
    #[serde(rename = "transferAmountC")]
    transfer_amount_c: Vec<String>,
    #[serde(rename = "transferAmountDSender")]
    transfer_amount_d_sender: Vec<String>,
    #[serde(rename = "transferAmountDRecipient")]
    transfer_amount_d_recipient: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct SigmaProofFixture {
    commitment: Vec<String>,
    response: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct DebugFixture {
    #[serde(rename = "newBalanceChunks")]
    new_balance_chunks: Vec<String>,
    #[allow(dead_code)]
    #[serde(rename = "truthfulNewBalanceChunks")]
    truthful_new_balance_chunks: Vec<String>,
    #[serde(rename = "overrideApplied")]
    override_applied: bool,
}

// =============================================================================
// Hex helpers
// =============================================================================

fn hex_decode(s: &str) -> Vec<u8> {
    let raw = s
        .strip_prefix("0x")
        .or_else(|| s.strip_prefix("0X"))
        .unwrap_or(s);
    assert_eq!(raw.len() % 2, 0, "hex string length must be even");
    let mut out = Vec::with_capacity(raw.len() / 2);
    for i in (0..raw.len()).step_by(2) {
        out.push(u8::from_str_radix(&raw[i..i + 2], 16).expect("hex byte"));
    }
    out
}

fn hex_32(s: &str) -> [u8; 32] {
    let bytes = hex_decode(s);
    assert_eq!(bytes.len(), 32, "expected 32 bytes (got {})", bytes.len());
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}

fn compressed_vec(items: &[String]) -> Vec<[u8; 32]> {
    items.iter().map(|s| hex_32(s)).collect()
}

// =============================================================================
// Fixture loader
// =============================================================================

const FIXTURE_DIR_REL: &str = "tests/fixtures/sigma_17";

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join(FIXTURE_DIR_REL)
        .join(format!("{name}.json"))
}

fn load_fixture(name: &str) -> Fixture {
    let path = fixture_path(name);
    let bytes = fs::read(&path).unwrap_or_else(|err| {
        panic!(
            "M10-g: failed to read fixture {}: {err}.\n\
             Regenerate via: cd operator-services && node scripts/gen_sigma_position_17_rust_fixtures.mjs",
            path.display()
        )
    });
    serde_json::from_slice::<Fixture>(&bytes).expect("M10-g: parse fixture json")
}

// =============================================================================
// Common build helpers
// =============================================================================

fn build_dst(stmt: &StatementFixture, ell: usize, n: usize, chain_id: u8) -> DomainSeparator {
    let sender = hex_32(&stmt.sender_address_hex);
    let recipient = hex_32(&stmt.recipient_address_hex);
    let asset = hex_32(&stmt.token_address_hex);
    let session =
        bcs_serialize_transfer_session(&sender, &recipient, &asset, ell as u64, n as u64, false, 0);
    DomainSeparator {
        contract_address: APTOS_FRAMEWORK_ADDRESS,
        chain_id,
        protocol_id: PROTOCOL_ID.as_bytes().to_vec(),
        session_id: session,
    }
}

fn build_statement_from_fixture(
    stmt: &StatementFixture,
) -> eunoma_crypto_worker::transfer_sigma_reference::Statement {
    let inputs = TransferStatementInputs {
        sender_ek: hex_32(&stmt.sender_ek_hex),
        recipient_ek: hex_32(&stmt.recipient_ek_hex),
        old_balance_c: compressed_vec(&stmt.old_balance_c),
        old_balance_d: compressed_vec(&stmt.old_balance_d),
        new_balance_c: compressed_vec(&stmt.new_balance_c),
        new_balance_d: compressed_vec(&stmt.new_balance_d),
        transfer_amount_c: compressed_vec(&stmt.transfer_amount_c),
        transfer_amount_d_sender: compressed_vec(&stmt.transfer_amount_d_sender),
        transfer_amount_d_recipient: compressed_vec(&stmt.transfer_amount_d_recipient),
    };
    build_statement(&inputs)
        .expect("M10-g: build_statement failed (compressed ciphertext bytes must decompress)")
}

fn build_proof_from_fixture(proof: &SigmaProofFixture) -> SigmaProtocolProof {
    SigmaProtocolProof {
        commitment: proof.commitment.iter().map(|s| hex_32(s)).collect(),
        response: proof.response.iter().map(|s| hex_32(s)).collect(),
    }
}

/// Run BOTH verifiers on the same fixture and return:
///   * the rust per-position fail mask (1 = position failed, 0 = position verified;
///     matches JS `failsByPosition[]` semantics for direct comparison)
///   * the rust aggregate boolean result from `verify_transfer_single_party`
fn run_rust_verifier(fix: &Fixture) -> (Vec<u8>, bool) {
    let stmt = build_statement_from_fixture(&fix.statement);
    let dst = build_dst(&fix.statement, fix.meta.ell, fix.meta.n, fix.meta.chain_id);
    let proof = build_proof_from_fixture(&fix.sigma_proof);

    // Per-position result.
    let per_position = verify_transfer_per_position_for_parity_tests(
        &proof,
        &stmt,
        &dst,
        fix.meta.ell,
        fix.meta.n,
        fix.meta.has_effective_auditor,
        fix.meta.num_volun_auditors,
    )
    .expect("M10-g: per-position verifier returned Err (auditor branch / shape mismatch?)");
    let fails: Vec<u8> = per_position
        .iter()
        .map(|verified| if *verified { 0u8 } else { 1u8 })
        .collect();

    // Aggregate boolean.
    let aggregate = verify_transfer_single_party(
        &proof,
        &stmt,
        &dst,
        fix.meta.ell,
        fix.meta.n,
        fix.meta.has_effective_auditor,
        fix.meta.num_volun_auditors,
    )
    .expect(
        "M10-g: verify_transfer_single_party returned Err (must surface only structural errors)",
    );
    (fails, aggregate)
}

// =============================================================================
// Per-fixture assertion helper: enforces rust↔JS parity AND the M10 plan's
// expected outcome (allPass, position-17 status).
// =============================================================================

fn assert_parity(fix: &Fixture, expected_failed_positions: &[usize]) {
    let (rust_fails, rust_aggregate) = run_rust_verifier(fix);

    // 1. Cross-implementation parity: rust per-position fail mask MUST equal
    //    the JS reference verifier's per-position fail mask byte-for-byte.
    assert_eq!(
        rust_fails,
        fix.meta.js_reference_verifier.fails_by_position,
        "M10-g[{}]: rust per-position fail mask diverges from JS reference verifier's.\n\
         description: {}\n\
         rust fails={:?}\n\
         js fails  ={:?}\n\
         If this diverges, ONE of the two reference verifiers is wrong — STOP and report.",
        fix.meta.name,
        fix.meta.description,
        rust_fails,
        fix.meta.js_reference_verifier.fails_by_position,
    );

    // 2. Aggregate boolean parity: rust's `verify_transfer_single_party`
    //    boolean MUST equal JS's `allPass`.
    assert_eq!(
        rust_aggregate, fix.meta.js_reference_verifier.all_pass,
        "M10-g[{}]: rust aggregate verify_transfer_single_party={} but JS allPass={}",
        fix.meta.name, rust_aggregate, fix.meta.js_reference_verifier.all_pass,
    );

    // 3. Internal consistency: aggregate boolean MUST equal "no position
    //    failed" computed from the per-position mask.
    let any_position_failed = rust_fails.iter().any(|v| *v == 1);
    assert_eq!(
        rust_aggregate, !any_position_failed,
        "M10-g[{}]: rust verifier internal inconsistency — aggregate={}, any_failed={}",
        fix.meta.name, rust_aggregate, any_position_failed,
    );

    // 4. Plan-mandated outcome: the set of failed positions MUST equal
    //    `expected_failed_positions` exactly.
    let actual_failed: Vec<usize> = rust_fails
        .iter()
        .enumerate()
        .filter_map(|(i, v)| if *v == 1 { Some(i) } else { None })
        .collect();
    assert_eq!(
        actual_failed, expected_failed_positions,
        "M10-g[{}]: failed positions {:?} != expected {:?}\n\
         description: {}",
        fix.meta.name, actual_failed, expected_failed_positions, fix.meta.description,
    );

    // 5. Sanity: fixture metadata must be on the shape the rust verifier
    //    accepts (ell=8, n=4, no auditor — the only branch the reference
    //    port implements).
    assert_eq!(
        fix.meta.ell, 8,
        "M10-g[{}]: ell != 8 — reference port unsupported",
        fix.meta.name
    );
    assert_eq!(
        fix.meta.n, 4,
        "M10-g[{}]: n != 4 — reference port unsupported",
        fix.meta.name
    );
    assert!(
        !fix.meta.has_effective_auditor,
        "M10-g[{}]: has_effective_auditor must be false",
        fix.meta.name
    );
    assert_eq!(
        fix.meta.num_volun_auditors, 0,
        "M10-g[{}]: num_volun_auditors must be 0",
        fix.meta.name
    );
}

// =============================================================================
// Tests (exactly the 4 cases the M10-g task description requires)
// =============================================================================

#[tokio::test]
async fn sigma_position_17_verifies_for_1_deposit_with_correct_new_a() {
    let fix = load_fixture("1_deposit_happy_path");
    // Plan-mandated 1-deposit baseline (M8 case): 100 octas / 100 octas xfer.
    assert_eq!(fix.meta.total_octas, "100", "{}", fix.meta.name);
    assert_eq!(fix.meta.transfer_octas, "100", "{}", fix.meta.name);
    assert!(
        !fix.debug.override_applied,
        "happy path must use truthful new_a"
    );
    assert_parity(&fix, &[]);
}

#[tokio::test]
async fn sigma_position_17_verifies_for_2_deposits_with_correct_new_a() {
    let fix = load_fixture("2_deposit_happy_path");
    assert_eq!(fix.meta.total_octas, "250", "{}", fix.meta.name);
    assert_eq!(fix.meta.transfer_octas, "100", "{}", fix.meta.name);
    assert!(
        !fix.debug.override_applied,
        "happy path must use truthful new_a"
    );
    assert_parity(&fix, &[]);
}

#[tokio::test]
async fn sigma_position_17_verifies_for_8_deposits_with_correct_new_a() {
    let fix = load_fixture("8_deposit_happy_path");
    // 8-deposit aggregate: 100+101+102+103+104+105+106+107 = 828.
    assert_eq!(fix.meta.total_octas, "828", "{}", fix.meta.name);
    assert_eq!(fix.meta.transfer_octas, "100", "{}", fix.meta.name);
    assert!(
        !fix.debug.override_applied,
        "happy path must use truthful new_a"
    );
    assert_parity(&fix, &[]);
}

#[tokio::test]
async fn sigma_position_17_fails_for_8_deposits_with_zero_new_a_regression_guard() {
    let fix = load_fixture("8_deposit_zero_new_a_regression");
    // Same 8-deposit chain state as the happy-path 828 case.
    assert_eq!(fix.meta.total_octas, "828", "{}", fix.meta.name);
    assert_eq!(fix.meta.transfer_octas, "100", "{}", fix.meta.name);
    assert!(
        fix.debug.override_applied,
        "regression fixture must use new_a override"
    );
    // new_a override is [0; ELL] — sanity-check the committed fixture bytes.
    for (idx, chunk) in fix.debug.new_balance_chunks.iter().enumerate() {
        assert_eq!(
            chunk, "0",
            "M10-g regression fixture: new_balance_chunks[{idx}] != 0 (got {chunk}); \
             fixture seed/SDK may have drifted — regenerate via gen_sigma_position_17_rust_fixtures.mjs"
        );
    }

    // Plan: σ position 17 (and ONLY position 17) must fail.
    assert_parity(&fix, &[17]);
}

// =============================================================================
// Additional sanity: every fixture is reachable / parses; covers a CI failure
// mode where a fixture is missing.
// =============================================================================

#[test]
fn all_four_fixtures_present_and_parse() {
    for name in [
        "1_deposit_happy_path",
        "2_deposit_happy_path",
        "8_deposit_happy_path",
        "8_deposit_zero_new_a_regression",
    ] {
        let path = fixture_path(name);
        assert!(
            Path::new(&path).exists(),
            "M10-g: missing fixture file {}",
            path.display()
        );
        let _fix = load_fixture(name);
    }
}
