/**
 * Aptos CA Transfer V1 — TS-side parity fixture generator.
 *
 * This test is the source of truth for the byte-for-byte transfer parity fixture
 * that the Rust side (milestone 4a commits 3-5) will load and assert equality
 * against. Running this test:
 *
 *   1. Installs a deterministic PRNG over `globalThis.crypto.getRandomValues` BEFORE
 *      the Aptos CA SDK + WASM bindings are loaded. The PRNG output is SHA-256
 *      counter-mode keyed by the seed string `EUNOMA_APTOS_CA_TRANSFER_V1_FIXTURE_PRNG_SEED`.
 *      This hook reaches BOTH paths the SDK reads randomness from:
 *        - `@noble/hashes/utils.randomBytes` (used by `ed25519GenRandom`, which feeds
 *          ElGamal blinding factors and the sigma protocol `alpha` nonce vector).
 *        - The Bulletproofs WASM binding (used by `batchRangeProof` for `s_L`, `s_R`,
 *          `t_1_blinding`, `t_2_blinding`). The WASM imports
 *          `__wbg_getRandomValues_*` which dispatches through `globalThis.crypto`.
 *
 *      The WASM RNG is internally cached AFTER the first 32 bytes are pulled at
 *      WASM-init time, but as long as the operation order is fixed (init → range
 *      proof #1 → range proof #2 → sigma proof), the resulting byte stream is
 *      stable across process invocations. We rely on that — see "DETERMINISM CONTRACT"
 *      below for the operations a future agent must reproduce.
 *
 *   2. Constructs sender/recipient decryption keys, addresses, and asset metadata
 *      deterministically (no live network calls).
 *
 *   3. Encrypts:
 *        - the old balance (8 chunks summing to 1000),
 *        - the transfer amount (4 chunks for 100),
 *        - the new balance (8 chunks for 900),
 *      using explicit randomness vectors drawn from the same PRNG (NOT the SDK's
 *      internal `ed25519GenListOfRandom`).
 *
 *   4. Calls the lower-level `proveTransfer({...})` SDK entry (NOT
 *      `ConfidentialTransfer.create()`, because that helper allocates randomness
 *      via `ed25519GenListOfRandom` in a way that's harder to thread). The sigma
 *      proof witness vector is `[dk, new_a[ell], new_r[ell], v[n], r[n]]` = 25
 *      scalars; the proof commitment vector has 30 points; both are persisted
 *      verbatim.
 *
 *   5. Calls `batchRangeProof({...})` for the amount (4 chunks, 16 bits) and the
 *      new balance (8 chunks, 16 bits). Bulletproofs go to BulletproofsRangeProof
 *      sub-protocol; the outer Merlin transcript label in the SDK's WASM binary is
 *        "AptosConfidentialAsset/BulletproofRangeProof"
 *      (verified by `strings` against
 *      `node_modules/@aptos-labs/confidential-asset-bindings/dist/aptos_confidential_asset_wasm_bg.wasm`).
 *      The bulletproofs-5.0.0 crate is used (also verified via WASM debug paths).
 *      Inner-loop labels (`"rangeproof v1"`, `"nmipp v1"`, `"dom-sep"`) are
 *      bulletproofs-internal and need not be configured by the Rust verifier — it
 *      should depend on bulletproofs-5.0.0 directly.
 *
 *   6. Verifies all three proofs (sigma + 2 range proofs), then writes the fixture
 *      to `tests/fixtures/aptos_ca_transfer_v1_fixture.json`. If the fixture
 *      already exists on disk, the test ALSO asserts byte-for-byte equality with
 *      the freshly regenerated bytes (proving the determinism contract holds).
 *
 *   Set `EUNOMA_REGENERATE_FIXTURES=1` to force the committed fixture to be
 *   overwritten (use only when intentionally rotating the canonical bytes).
 *
 * ===========================================================================
 * DETERMINISM CONTRACT — preserve these in this order, do not re-order:
 *
 *   crypto.getRandomValues hook installed
 *   noble `randomBytes` pulls (sequential):
 *     - oldBalanceRandomness  : ell = 8 scalars  (rejection-sampled mod n)
 *     - transferAmountRandomness : n = 4 scalars
 *     - newBalanceRandomness  : ell = 8 scalars
 *     - sigma alpha           : k = 25 scalars   (consumed inside proveTransfer)
 *   WASM first 32 bytes (consumed by bulletproofs RNG seed at WASM-init time of
 *     the first batchRangeProof call):
 *     - batchRangeProof(amount, 4 vals, 16 bits)
 *     - batchRangeProof(newBalance, 8 vals, 16 bits)
 *
 * Reordering ANY of these will produce different bytes.
 * ===========================================================================
 */

import { sha256 } from "@noble/hashes/sha256";

// -------- Deterministic PRNG (must be installed BEFORE the SDK imports execute) ----------
const PRNG_SEED = new TextEncoder().encode(
  "EUNOMA_APTOS_CA_TRANSFER_V1_FIXTURE_PRNG_SEED",
);
const prngBlocks: Uint8Array[] = [];
let prngConsumed = 0;

function ensurePrngBlock(idx: number): void {
  while (prngBlocks.length <= idx) {
    const counter = new Uint8Array(8);
    new DataView(counter.buffer).setBigUint64(0, BigInt(prngBlocks.length), false);
    const combined = new Uint8Array(PRNG_SEED.length + counter.length);
    combined.set(PRNG_SEED, 0);
    combined.set(counter, PRNG_SEED.length);
    prngBlocks.push(sha256(combined));
  }
}

function prngFill(buf: Uint8Array): Uint8Array {
  for (let i = 0; i < buf.length; i += 1) {
    const blockIdx = Math.floor(prngConsumed / 32);
    const inBlock = prngConsumed % 32;
    ensurePrngBlock(blockIdx);
    buf[i] = prngBlocks[blockIdx][inBlock];
    prngConsumed += 1;
  }
  return buf;
}

Object.defineProperty(globalThis.crypto, "getRandomValues", {
  value: function deterministicGetRandomValues(buf: Uint8Array): Uint8Array {
    return prngFill(buf);
  },
  writable: true,
  configurable: true,
});

// -------- SDK imports (after PRNG installed) ----------
import { describe, expect, it } from "vitest";
import {
  AVAILABLE_BALANCE_CHUNK_COUNT,
  CHUNK_BITS,
  ChunkedAmount,
  H_RISTRETTO,
  RistrettoPoint,
  TRANSFER_AMOUNT_CHUNK_COUNT,
  TwistedEd25519PrivateKey,
  TwistedElGamal,
  proveTransfer,
  verifyTransfer,
} from "@aptos-labs/confidential-asset";
import {
  batchRangeProof,
  batchVerifyProof,
} from "@aptos-labs/confidential-asset-bindings";
import { numberToBytesLE } from "@noble/curves/abstract/utils";
import { ed25519 } from "@noble/curves/ed25519";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const FIXTURE_PATH = resolve(
  __filename,
  "..",
  "fixtures",
  "aptos_ca_transfer_v1_fixture.json",
);

// -------- Fixture deterministic inputs ----------
function dkBytesFor(mul: number, add: number): Uint8Array {
  const out = new Uint8Array(32);
  for (let i = 0; i < 32; i += 1) out[i] = (i * mul + add) & 0xff;
  // Clear top nibble to guarantee the scalar is < 2^252, well below curve order.
  out[31] &= 0x0f;
  return out;
}

function fillAddr(seed: number): Uint8Array {
  const a = new Uint8Array(32);
  for (let i = 0; i < 32; i += 1) a[i] = (i + seed) & 0xff;
  return a;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

function scalarBytesLE(s: bigint): string {
  return bytesToHex(numberToBytesLE(s, 32));
}

function genListOfDeterministicScalars(count: number): bigint[] {
  // Mirrors `ed25519GenListOfRandom` (rejection-sampled mod CURVE.n, big-endian
  // bytes-to-bigint). We call it explicitly here so the randomness is consumed
  // BEFORE the SDK does, giving us blinding factors we can pass to `proveTransfer`.
  const out: bigint[] = [];
  for (let i = 0; i < count; i += 1) {
    let s: bigint;
    do {
      const buf = new Uint8Array(32);
      globalThis.crypto.getRandomValues(buf);
      let r = 0n;
      for (let j = 0; j < 32; j += 1) {
        r = (r << 8n) | BigInt(buf[j]);
      }
      s = r;
    } while (s > ed25519.CURVE.n);
    out.push(s);
  }
  return out;
}

function encryptChunks(
  chunks: bigint[],
  ekKey: ReturnType<TwistedEd25519PrivateKey["publicKey"]>,
  randomness: bigint[],
): Array<ReturnType<typeof TwistedElGamal.encryptWithPK>> {
  return chunks.map((chunk, i) =>
    TwistedElGamal.encryptWithPK(chunk, ekKey, randomness[i]),
  );
}

describe("Aptos CA transfer parity fixture", () => {
  it("generates and verifies the byte-locked transfer fixture", async () => {
    // -------- Inputs ----------
    const senderDk = new TwistedEd25519PrivateKey(dkBytesFor(7, 3));
    const senderEk = senderDk.publicKey();
    const recipientDk = new TwistedEd25519PrivateKey(dkBytesFor(11, 5));
    const recipientEk = recipientDk.publicKey();

    const senderAddress = fillAddr(1);
    const recipientAddress = fillAddr(2);
    const tokenAddress = fillAddr(3);
    const chainId = 2;

    const ell = AVAILABLE_BALANCE_CHUNK_COUNT;
    const n = TRANSFER_AMOUNT_CHUNK_COUNT;
    expect(ell).toBe(8);
    expect(n).toBe(4);

    const oldBalance = 1000n;
    const transferAmount = 100n;
    const newBalance = oldBalance - transferAmount;
    const oldBalanceChunks = ChunkedAmount.fromAmount(oldBalance).amountChunks;
    const newBalanceChunks = ChunkedAmount.fromAmount(newBalance).amountChunks;
    const transferAmountChunks =
      ChunkedAmount.createTransferAmount(transferAmount).amountChunks;

    expect(oldBalanceChunks).toHaveLength(ell);
    expect(newBalanceChunks).toHaveLength(ell);
    expect(transferAmountChunks).toHaveLength(n);
    expect(oldBalanceChunks[0]).toBe(1000n);
    expect(newBalanceChunks[0]).toBe(900n);
    expect(transferAmountChunks[0]).toBe(100n);

    // -------- PRNG-derived blinding factors ----------
    // Order matters — see DETERMINISM CONTRACT.
    const oldBalanceRandomness = genListOfDeterministicScalars(ell);
    const transferAmountRandomness = genListOfDeterministicScalars(n);
    const newBalanceRandomness = genListOfDeterministicScalars(ell);

    // -------- Ciphertexts ----------
    const oldBalanceCt = encryptChunks(
      oldBalanceChunks,
      senderEk,
      oldBalanceRandomness,
    );
    const newBalanceCt = encryptChunks(
      newBalanceChunks,
      senderEk,
      newBalanceRandomness,
    );
    const transferSenderCt = encryptChunks(
      transferAmountChunks,
      senderEk,
      transferAmountRandomness,
    );
    const transferRecipientCt = encryptChunks(
      transferAmountChunks,
      recipientEk,
      transferAmountRandomness,
    );

    const oldBalanceC = oldBalanceCt.map((ct) => ct.C);
    const oldBalanceD = oldBalanceCt.map((ct) => ct.D);
    const newBalanceC = newBalanceCt.map((ct) => ct.C);
    const newBalanceD = newBalanceCt.map((ct) => ct.D);
    const transferAmountC = transferSenderCt.map((ct) => ct.C);
    const transferAmountDSender = transferSenderCt.map((ct) => ct.D);
    const transferAmountDRecipient = transferRecipientCt.map((ct) => ct.D);

    // Sanity: sender's and recipient's transfer-amount commitments share C (same m·G + r·H).
    for (let i = 0; i < n; i += 1) {
      expect(transferSenderCt[i].C.equals(transferRecipientCt[i].C)).toBe(true);
    }

    // -------- Range proofs (WASM RNG consumed here for the first time) ----------
    const valBase = RistrettoPoint.BASE.toRawBytes();
    const randBase = H_RISTRETTO.toRawBytes();

    const rangeAmountResult = await batchRangeProof({
      v: transferAmountChunks,
      rs: transferAmountRandomness.map((r) => numberToBytesLE(r, 32)),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });
    const rangeNewBalanceResult = await batchRangeProof({
      v: newBalanceChunks,
      rs: newBalanceRandomness.map((r) => numberToBytesLE(r, 32)),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });

    // -------- Sigma proof ----------
    const sigmaProof = proveTransfer({
      dk: senderDk,
      senderAddress,
      recipientAddress,
      tokenAddress,
      chainId,
      senderEncryptionKey: senderEk,
      recipientEncryptionKey: recipientEk,
      oldBalanceC,
      oldBalanceD,
      newBalanceC,
      newBalanceD,
      newAmountChunks: newBalanceChunks,
      newRandomness: newBalanceRandomness,
      transferAmountC,
      transferAmountDSender,
      transferAmountDRecipient,
      transferAmountChunks,
      transferRandomness: transferAmountRandomness,
      hasEffectiveAuditor: false,
    });

    // Sigma proof shape: 30 commitment points, 25 response scalars
    expect(sigmaProof.commitment).toHaveLength(30);
    expect(sigmaProof.response).toHaveLength(25);
    for (const c of sigmaProof.commitment) expect(c).toHaveLength(32);
    for (const r of sigmaProof.response) expect(r).toHaveLength(32);

    // -------- Verify all three proofs ----------
    const sigmaOk = verifyTransfer({
      senderAddress,
      recipientAddress,
      tokenAddress,
      chainId,
      ekSidBytes: senderEk.toUint8Array(),
      ekRidBytes: recipientEk.toUint8Array(),
      oldBalanceC,
      oldBalanceD,
      newBalanceC,
      newBalanceD,
      transferAmountC,
      transferAmountDSender,
      transferAmountDRecipient,
      hasEffectiveAuditor: false,
      proof: sigmaProof,
    });
    expect(sigmaOk).toBe(true);

    const rangeAmountOk = await batchVerifyProof({
      proof: rangeAmountResult.proof,
      comms: transferAmountC.map((p) => p.toRawBytes()),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });
    expect(rangeAmountOk).toBe(true);

    const rangeNewBalanceOk = await batchVerifyProof({
      proof: rangeNewBalanceResult.proof,
      comms: newBalanceC.map((p) => p.toRawBytes()),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });
    expect(rangeNewBalanceOk).toBe(true);

    // -------- Assemble fixture JSON ----------
    const fixture = {
      version: "aptos_ca_transfer_v1",
      generator: {
        sdk: "@aptos-labs/confidential-asset@1.1.1",
        bindings: "@aptos-labs/confidential-asset-bindings@1.1.1",
        bulletproofsCrate: "bulletproofs-5.0.0",
        merlinCrate: "merlin-3.0.0",
        outerTranscriptLabel: "AptosConfidentialAsset/BulletproofRangeProof",
        sigmaProtocolId: "AptosConfidentialAsset/TransferV1",
        sigmaTypeName: "0x1::sigma_protocol_transfer::Transfer",
        prngSeed: new TextDecoder().decode(PRNG_SEED),
        determinism:
          "globalThis.crypto.getRandomValues patched to SHA-256 counter-mode " +
          "keyed by prngSeed; both noble randomBytes and Aptos WASM bulletproofs " +
          "consume from this stream. Operation order is locked in the test.",
      },
      params: {
        ell,
        n,
        chunkBits: CHUNK_BITS,
        hasAuditor: false,
        numAuditors: 0,
        amount: Number(transferAmount),
        oldBalance: Number(oldBalance),
        newBalance: Number(newBalance),
      },
      witness: {
        dk: "0x" + bytesToHex(senderDk.toUint8Array()),
      },
      statement: {
        senderAddress: "0x" + bytesToHex(senderAddress),
        recipientAddress: "0x" + bytesToHex(recipientAddress),
        tokenAddress: "0x" + bytesToHex(tokenAddress),
        chainId,
        senderEk: "0x" + bytesToHex(senderEk.toUint8Array()),
        recipientEk: "0x" + bytesToHex(recipientEk.toUint8Array()),
      },
      plaintextChunks: {
        oldBalance: oldBalanceChunks.map((c) => c.toString()),
        newBalance: newBalanceChunks.map((c) => c.toString()),
        transferAmount: transferAmountChunks.map((c) => c.toString()),
      },
      randomness: {
        oldBalance: oldBalanceRandomness.map((r) => "0x" + scalarBytesLE(r)),
        transferAmount: transferAmountRandomness.map(
          (r) => "0x" + scalarBytesLE(r),
        ),
        newBalance: newBalanceRandomness.map((r) => "0x" + scalarBytesLE(r)),
      },
      ciphertexts: {
        oldBalanceC: oldBalanceC.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        oldBalanceD: oldBalanceD.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        newBalanceC: newBalanceC.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        newBalanceD: newBalanceD.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        amountC: transferAmountC.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        amountDSender: transferAmountDSender.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
        amountDRecipient: transferAmountDRecipient.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
      },
      sigmaProof: {
        commitment: sigmaProof.commitment.map((b) => "0x" + bytesToHex(b)),
        response: sigmaProof.response.map((b) => "0x" + bytesToHex(b)),
        witnessLayout: ["dk", "new_a[ell]", "new_r[ell]", "v[n]", "r[n]"],
        commitmentLayout: [
          "ek_sid * dk",
          "G*new_a[i] + H*new_r[i] for i in [ell]",
          "ek_sid * new_r[i] for i in [ell]",
          "balance equation: dk*<B,old_R> + (<B,new_a> + <B,v>)*G",
          "G*v[j] + H*r[j] for j in [n]",
          "ek_sid * r[j] for j in [n]",
          "ek_rid * r[j] for j in [n]",
        ],
      },
      rangeProofs: {
        amount: {
          numValues: n,
          numBits: CHUNK_BITS,
          proof: "0x" + bytesToHex(rangeAmountResult.proof),
          comms: rangeAmountResult.comms.map((c) => "0x" + bytesToHex(c)),
        },
        newBalance: {
          numValues: ell,
          numBits: CHUNK_BITS,
          proof: "0x" + bytesToHex(rangeNewBalanceResult.proof),
          comms: rangeNewBalanceResult.comms.map((c) => "0x" + bytesToHex(c)),
        },
      },
      // The on-chain `confidential_transfer_raw(...)` function arguments in the
      // order Aptos CA's TS SDK encodes them. The Rust side can re-derive each
      // entry from the fields above; this section is provided as a sanity
      // cross-check.
      onChainArgs: {
        new_balance_C: newBalanceC.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        new_balance_D: newBalanceD.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        new_balance_A: [], // no effective auditor
        sender_amount_C: transferAmountC.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
        sender_amount_D: transferAmountDSender.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
        recipient_amount_D: transferAmountDRecipient.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
        effective_auditor_amount_D: [],
        voluntary_auditor_eks: [],
        voluntary_auditor_amount_D: [],
        range_proof_new_balance:
          "0x" + bytesToHex(rangeNewBalanceResult.proof),
        range_proof_amount: "0x" + bytesToHex(rangeAmountResult.proof),
        sigma_commitment: sigmaProof.commitment.map(
          (b) => "0x" + bytesToHex(b),
        ),
        sigma_response: sigmaProof.response.map((b) => "0x" + bytesToHex(b)),
        memo: "0x",
      },
      prng: {
        bytesConsumedThroughSigmaProof: prngConsumed,
      },
    };

    const fixtureJson = JSON.stringify(fixture, null, 2) + "\n";

    // -------- Persist / Re-verify ----------
    const regenerate = process.env.EUNOMA_REGENERATE_FIXTURES === "1";
    if (!existsSync(FIXTURE_PATH) || regenerate) {
      writeFileSync(FIXTURE_PATH, fixtureJson);
    }
    const onDisk = readFileSync(FIXTURE_PATH, "utf8");
    expect(onDisk).toBe(fixtureJson);
  });
});

// =============================================================================================
// M4 end-to-end dk-threshold sigma byte-parity test.
//
// Verifies the M4 dk-threshold construction produces a sigma proof that the Aptos SDK's
// verifyTransfer accepts. Wire:
//   1. Build canonical Statement + witness (same fixture as above).
//   2. Drive single-party proveTransfer → canonical {commitment[30], response[25]}.
//   3. Recover the canonical α[0] from the canonical response[0]:
//          response[0] = α[0] + e · witness[0] = α[0] + e · dk
//          α[0]        = response[0] − e · dk  (mod n)
//      (e is recomputed via sigmaProtocolFiatShamir over the canonical commitment.)
//   4. Split α[0] into 5 fresh α_share scalars (sum = α[0]).
//   5. Build a Shamir polynomial of degree 4 with f(0) = dk; dk_share_j = f(slot_j + 1).
//      Reconstruct dk = Σ_j λ_j · dk_share_j with Lagrange coefficients at x=0.
//   6. Per-worker s_share_j = α_share_j + e · (λ_j · dk_share_j).
//   7. Aggregate s[0]_threshold = Σ_j s_share_j.
//   8. KILLER ASSERTIONS:
//      (a) s[0]_threshold byte-equals the canonical response[0].
//      (b) Substituting s[0]_threshold for response[0] in the canonical proof + passing
//          to verifyTransfer still returns true.
//   9. Aptos CA TransferV1 commitment/response shapes preserved (30 / 25, 32 bytes each).
//
// This proves the M4 threshold algebra is byte-canonical with the single-party prover that
// the chain verifier accepts. The Rust worker computes the SAME s_share via the same algebra;
// the M4-c3 5-worker killer test verifies the per-worker equation. M4-c5 closes the loop:
// the threshold-aggregated proof is accepted by the Aptos SDK byte-canonical verifier.
// =============================================================================================
describe("Aptos CA transfer M4 end-to-end dk-threshold byte-parity", () => {
  it("M4 threshold-aggregated sigma proof byte-equals + verifies via Aptos SDK", async () => {
    // -------- Inputs (same fixture as the single-party test) ----------
    const senderDk = new TwistedEd25519PrivateKey(dkBytesFor(7, 3));
    const senderEk = senderDk.publicKey();
    const recipientDk = new TwistedEd25519PrivateKey(dkBytesFor(11, 5));
    const recipientEk = recipientDk.publicKey();

    const senderAddress = fillAddr(1);
    const recipientAddress = fillAddr(2);
    const tokenAddress = fillAddr(3);
    const chainId = 2;

    const ell = AVAILABLE_BALANCE_CHUNK_COUNT;
    const n = TRANSFER_AMOUNT_CHUNK_COUNT;

    const oldBalance = 1000n;
    const transferAmount = 100n;
    const newBalance = oldBalance - transferAmount;
    const oldBalanceChunks = ChunkedAmount.fromAmount(oldBalance).amountChunks;
    const newBalanceChunks = ChunkedAmount.fromAmount(newBalance).amountChunks;
    const transferAmountChunks =
      ChunkedAmount.createTransferAmount(transferAmount).amountChunks;

    const oldBalanceRandomness = genListOfDeterministicScalars(ell);
    const transferAmountRandomness = genListOfDeterministicScalars(n);
    const newBalanceRandomness = genListOfDeterministicScalars(ell);

    const oldBalanceCt = encryptChunks(
      oldBalanceChunks,
      senderEk,
      oldBalanceRandomness,
    );
    const newBalanceCt = encryptChunks(
      newBalanceChunks,
      senderEk,
      newBalanceRandomness,
    );
    const transferSenderCt = encryptChunks(
      transferAmountChunks,
      senderEk,
      transferAmountRandomness,
    );
    const transferRecipientCt = encryptChunks(
      transferAmountChunks,
      recipientEk,
      transferAmountRandomness,
    );

    const oldBalanceC = oldBalanceCt.map((ct) => ct.C);
    const oldBalanceD = oldBalanceCt.map((ct) => ct.D);
    const newBalanceC = newBalanceCt.map((ct) => ct.C);
    const newBalanceD = newBalanceCt.map((ct) => ct.D);
    const transferAmountC = transferSenderCt.map((ct) => ct.C);
    const transferAmountDSender = transferSenderCt.map((ct) => ct.D);
    const transferAmountDRecipient = transferRecipientCt.map((ct) => ct.D);

    // Drive single-party prove (WASM RNG consumed by batchRangeProof first).
    const valBase = RistrettoPoint.BASE.toRawBytes();
    const randBase = H_RISTRETTO.toRawBytes();
    await batchRangeProof({
      v: transferAmountChunks,
      rs: transferAmountRandomness.map((r) => numberToBytesLE(r, 32)),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });
    await batchRangeProof({
      v: newBalanceChunks,
      rs: newBalanceRandomness.map((r) => numberToBytesLE(r, 32)),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });

    const canonicalProof = proveTransfer({
      dk: senderDk,
      senderAddress,
      recipientAddress,
      tokenAddress,
      chainId,
      senderEncryptionKey: senderEk,
      recipientEncryptionKey: recipientEk,
      oldBalanceC,
      oldBalanceD,
      newBalanceC,
      newBalanceD,
      newAmountChunks: newBalanceChunks,
      newRandomness: newBalanceRandomness,
      transferAmountC,
      transferAmountDSender,
      transferAmountDRecipient,
      transferAmountChunks,
      transferRandomness: transferAmountRandomness,
      hasEffectiveAuditor: false,
    });

    expect(canonicalProof.commitment).toHaveLength(30);
    expect(canonicalProof.response).toHaveLength(25);

    // -------- Recover canonical α[0] from the proof + recompute e ----------
    const { sigmaProtocolFiatShamir, APTOS_FRAMEWORK_ADDRESS, bcsSerializeTransferSession } =
      await import("@aptos-labs/confidential-asset");
    const PROTOCOL_ID_BYTES = new TextEncoder().encode(
      "AptosConfidentialAsset/TransferV1",
    );
    const TYPE_NAME = "0x1::sigma_protocol_transfer::Transfer";

    // Build statement points (G, H, ek_sid, ek_rid, then 7 ciphertext groups).
    const G = RistrettoPoint.BASE;
    const H = H_RISTRETTO;
    const ekSid = senderEk;
    const ekSidBytes = ekSid.toUint8Array();
    const stmtPoints: ReturnType<typeof RistrettoPoint.fromHex>[] = [
      G,
      H,
      RistrettoPoint.fromHex(ekSidBytes),
      RistrettoPoint.fromHex(recipientEk.toUint8Array()),
    ];
    const stmtCompressed: Uint8Array[] = [
      G.toRawBytes(),
      H.toRawBytes(),
      ekSidBytes,
      recipientEk.toUint8Array(),
    ];
    const pushGroup = (group: (typeof newBalanceC)[number][]) => {
      for (const p of group) {
        stmtPoints.push(p);
        stmtCompressed.push(p.toRawBytes());
      }
    };
    pushGroup(oldBalanceC);
    pushGroup(oldBalanceD);
    pushGroup(newBalanceC);
    pushGroup(newBalanceD);
    pushGroup(transferAmountC);
    pushGroup(transferAmountDSender);
    pushGroup(transferAmountDRecipient);
    const stmt = { points: stmtPoints, compressedPoints: stmtCompressed, scalars: [] };

    const sessionId = bcsSerializeTransferSession(
      senderAddress,
      recipientAddress,
      tokenAddress,
      ell,
      n,
      false,
      0,
    );
    const dst = {
      contractAddress: APTOS_FRAMEWORK_ADDRESS,
      chainId,
      protocolId: PROTOCOL_ID_BYTES,
      sessionId,
    };
    const { e } = sigmaProtocolFiatShamir(
      dst,
      TYPE_NAME,
      stmt,
      canonicalProof.commitment,
      25,
    );

    const ED_N = ed25519.CURVE.n;
    const modN = (x: bigint) => ((x % ED_N) + ED_N) % ED_N;
    function modInverseN(a: bigint): bigint {
      // Fermat's little theorem: a^(n-2) mod n.
      let result = 1n;
      let base = modN(a);
      let exp = ED_N - 2n;
      while (exp > 0n) {
        if (exp & 1n) result = (result * base) % ED_N;
        base = (base * base) % ED_N;
        exp >>= 1n;
      }
      return result;
    }

    const responseScalars = canonicalProof.response.map((r) => {
      // bytesToNumberLE
      let value = 0n;
      for (let i = 31; i >= 0; i -= 1) {
        value = (value << 8n) | BigInt(r[i]);
      }
      return value;
    });

    // dk (as bigint LE bytes) — `proveTransfer` uses `bytesToNumberLE` on dk.
    let dkBigint = 0n;
    {
      const dkBytes = senderDk.toUint8Array();
      for (let i = 31; i >= 0; i -= 1) {
        dkBigint = (dkBigint << 8n) | BigInt(dkBytes[i]);
      }
    }
    const dkMod = modN(dkBigint);

    // α[0] = response[0] − e · dk  (mod n)
    const alphaZeroCanonical = modN(responseScalars[0] - modN(e * dkMod));

    // -------- M4 threshold construction ----------
    // 1. Split α[0] into 5 fresh α_share scalars summing to α[0].
    const alphaShares: bigint[] = [];
    let sumSoFar = 0n;
    // Use the existing PRNG-deterministic scalar generator for reproducibility.
    const aRandoms = genListOfDeterministicScalars(4);
    for (let j = 0; j < 4; j += 1) {
      const s = modN(aRandoms[j]);
      alphaShares.push(s);
      sumSoFar = modN(sumSoFar + s);
    }
    alphaShares.push(modN(alphaZeroCanonical - sumSoFar));
    // Sanity: Σ α_share == α[0] canonical.
    const alphaZeroFromShares = alphaShares.reduce((a, b) => modN(a + b), 0n);
    expect(alphaZeroFromShares).toBe(alphaZeroCanonical);

    // 2. Build a degree-4 Shamir polynomial f(x) with f(0) = dk.
    const selectedSlots = [0, 1, 2, 3, 4];
    const polyRandoms = genListOfDeterministicScalars(4);
    const polyCoeffs: bigint[] = [dkMod];
    for (let i = 0; i < 4; i += 1) polyCoeffs.push(modN(polyRandoms[i]));
    function evalPolyAt(x: bigint): bigint {
      // Horner's method
      let acc = polyCoeffs[polyCoeffs.length - 1];
      for (let i = polyCoeffs.length - 2; i >= 0; i -= 1) {
        acc = modN(acc * x + polyCoeffs[i]);
      }
      return acc;
    }
    const dkShares: bigint[] = selectedSlots.map((slot) =>
      evalPolyAt(BigInt(slot + 1)),
    );

    // 3. Lagrange coefficients λ_j at x=0.
    const lambdas: bigint[] = selectedSlots.map((_, j) => {
      const xj = BigInt(selectedSlots[j] + 1);
      let num = 1n;
      let den = 1n;
      for (let k = 0; k < selectedSlots.length; k += 1) {
        if (k === j) continue;
        const xk = BigInt(selectedSlots[k] + 1);
        num = modN(num * modN(0n - xk));
        den = modN(den * modN(xj - xk));
      }
      return modN(num * modInverseN(den));
    });
    // Sanity: Σ λ_j · dk_share_j ≡ dk (mod n).
    const dkFromShares = lambdas.reduce(
      (acc, lam, j) => modN(acc + lam * dkShares[j]),
      0n,
    );
    expect(dkFromShares).toBe(dkMod);

    // 4. Per-worker s_share_j = α_share_j + e · (λ_j · dk_share_j).
    const sShares: bigint[] = selectedSlots.map((_, j) =>
      modN(alphaShares[j] + e * modN(lambdas[j] * dkShares[j])),
    );

    // 5. Aggregate s[0]_threshold = Σ_j s_share_j.
    const sZeroThreshold = sShares.reduce((acc, s) => modN(acc + s), 0n);

    // KILLER (a): s[0]_threshold byte-equals canonical response[0].
    expect(sZeroThreshold).toBe(responseScalars[0]);

    // 6. Build the threshold proof = canonical commitments with s[0] replaced by threshold value.
    const sZeroBytes = numberToBytesLE(sZeroThreshold, 32);
    const thresholdResponse = canonicalProof.response.map((bytes, i) =>
      i === 0 ? sZeroBytes : bytes,
    );
    expect(thresholdResponse[0]).toEqual(canonicalProof.response[0]);
    const thresholdProof = {
      commitment: canonicalProof.commitment,
      response: thresholdResponse,
    };

    // KILLER (b): Aptos SDK verifyTransfer accepts the threshold-reconstructed proof.
    const verifyOk = verifyTransfer({
      senderAddress,
      recipientAddress,
      tokenAddress,
      chainId,
      ekSidBytes,
      ekRidBytes: recipientEk.toUint8Array(),
      oldBalanceC,
      oldBalanceD,
      newBalanceC,
      newBalanceD,
      transferAmountC,
      transferAmountDSender,
      transferAmountDRecipient,
      hasEffectiveAuditor: false,
      proof: thresholdProof,
    });
    expect(verifyOk).toBe(true);
  });
});
