/**
 * Aptos CA Transfer V1 — TS-side parity fixture generator.
 *
 * This test is the source of truth for the byte-for-byte transfer parity fixture
 * that the Rust side (milestone 4a commits 3-5) will load and assert equality
 * against. Running this test:
 *
 *   1. Installs a deterministic PRNG over `globalThis.crypto.getRandomValues` BEFORE
 *      the Aptos CA SDK + WASM bindings are loaded. The PRNG output is SHA-256
 *      counter-mode keyed by the seed string `EUNOMA_APTOS_CA_TRANSFER_V1_FIXTURE_PRNG_SEED`.
 *      This hook reaches BOTH paths the SDK reads randomness from:
 *        - `@noble/hashes/utils.randomBytes` (used by `ed25519GenRandom`, which feeds
 *          ElGamal blinding factors and the sigma protocol `alpha` nonce vector).
 *        - The Bulletproofs WASM binding (used by `batchRangeProof` for `s_L`, `s_R`,
 *          `t_1_blinding`, `t_2_blinding`). The WASM imports
 *          `__wbg_getRandomValues_*` which dispatches through `globalThis.crypto`.
 *
 *      The WASM RNG is internally cached AFTER the first 32 bytes are pulled at
 *      WASM-init time, but as long as the operation order is fixed (init → range
 *      proof #1 → range proof #2 → sigma proof), the resulting byte stream is
 *      stable across process invocations. We rely on that — see "DETERMINISM CONTRACT"
 *      below for the operations a future agent must reproduce.
 *
 *   2. Constructs sender/recipient decryption keys, addresses, and asset metadata
 *      deterministically (no live network calls).
 *
 *   3. Encrypts:
 *        - the old balance (8 chunks summing to 1000),
 *        - the transfer amount (4 chunks for 100),
 *        - the new balance (8 chunks for 900),
 *      using explicit randomness vectors drawn from the same PRNG (NOT the SDK's
 *      internal `ed25519GenListOfRandom`).
 *
 *   4. Calls the lower-level `proveTransfer({...})` SDK entry (NOT
 *      `ConfidentialTransfer.create()`, because that helper allocates randomness
 *      via `ed25519GenListOfRandom` in a way that's harder to thread). The sigma
 *      proof witness vector is `[dk, new_a[ell], new_r[ell], v[n], r[n]]` = 25
 *      scalars; the proof commitment vector has 30 points; both are persisted
 *      verbatim.
 *
 *   5. Calls `batchRangeProof({...})` for the amount (4 chunks, 16 bits) and the
 *      new balance (8 chunks, 16 bits). Bulletproofs go to BulletproofsRangeProof
 *      sub-protocol; the outer Merlin transcript label in the SDK's WASM binary is
 *        "AptosConfidentialAsset/BulletproofRangeProof"
 *      (verified by `strings` against
 *      `node_modules/@aptos-labs/confidential-asset-bindings/dist/aptos_confidential_asset_wasm_bg.wasm`).
 *      The bulletproofs-5.0.0 crate is used (also verified via WASM debug paths).
 *      Inner-loop labels (`"rangeproof v1"`, `"nmipp v1"`, `"dom-sep"`) are
 *      bulletproofs-internal and need not be configured by the Rust verifier — it
 *      should depend on bulletproofs-5.0.0 directly.
 *
 *   6. Verifies all three proofs (sigma + 2 range proofs), then writes the fixture
 *      to `tests/fixtures/aptos_ca_transfer_v1_fixture.json`. If the fixture
 *      already exists on disk, the test ALSO asserts byte-for-byte equality with
 *      the freshly regenerated bytes (proving the determinism contract holds).
 *
 *   Set `EUNOMA_REGENERATE_FIXTURES=1` to force the committed fixture to be
 *   overwritten (use only when intentionally rotating the canonical bytes).
 *
 * ===========================================================================
 * DETERMINISM CONTRACT — preserve these in this order, do not re-order:
 *
 *   crypto.getRandomValues hook installed
 *   noble `randomBytes` pulls (sequential):
 *     - oldBalanceRandomness  : ell = 8 scalars  (rejection-sampled mod n)
 *     - transferAmountRandomness : n = 4 scalars
 *     - newBalanceRandomness  : ell = 8 scalars
 *     - sigma alpha           : k = 25 scalars   (consumed inside proveTransfer)
 *   WASM first 32 bytes (consumed by bulletproofs RNG seed at WASM-init time of
 *     the first batchRangeProof call):
 *     - batchRangeProof(amount, 4 vals, 16 bits)
 *     - batchRangeProof(newBalance, 8 vals, 16 bits)
 *
 * Reordering ANY of these will produce different bytes.
 * ===========================================================================
 */

import { sha256 } from "@noble/hashes/sha256";

// -------- Deterministic PRNG (must be installed BEFORE the SDK imports execute) ----------
const PRNG_SEED = new TextEncoder().encode(
  "EUNOMA_APTOS_CA_TRANSFER_V1_FIXTURE_PRNG_SEED",
);
const prngBlocks: Uint8Array[] = [];
let prngConsumed = 0;

function ensurePrngBlock(idx: number): void {
  while (prngBlocks.length <= idx) {
    const counter = new Uint8Array(8);
    new DataView(counter.buffer).setBigUint64(0, BigInt(prngBlocks.length), false);
    const combined = new Uint8Array(PRNG_SEED.length + counter.length);
    combined.set(PRNG_SEED, 0);
    combined.set(counter, PRNG_SEED.length);
    prngBlocks.push(sha256(combined));
  }
}

function prngFill(buf: Uint8Array): Uint8Array {
  for (let i = 0; i < buf.length; i += 1) {
    const blockIdx = Math.floor(prngConsumed / 32);
    const inBlock = prngConsumed % 32;
    ensurePrngBlock(blockIdx);
    buf[i] = prngBlocks[blockIdx][inBlock];
    prngConsumed += 1;
  }
  return buf;
}

Object.defineProperty(globalThis.crypto, "getRandomValues", {
  value: function deterministicGetRandomValues(buf: Uint8Array): Uint8Array {
    return prngFill(buf);
  },
  writable: true,
  configurable: true,
});

// -------- SDK imports (after PRNG installed) ----------
import { describe, expect, it } from "vitest";
import {
  AVAILABLE_BALANCE_CHUNK_COUNT,
  CHUNK_BITS,
  ChunkedAmount,
  H_RISTRETTO,
  RistrettoPoint,
  TRANSFER_AMOUNT_CHUNK_COUNT,
  TwistedEd25519PrivateKey,
  TwistedElGamal,
  proveTransfer,
  verifyTransfer,
} from "@aptos-labs/confidential-asset";
import {
  batchRangeProof,
  batchVerifyProof,
} from "@aptos-labs/confidential-asset-bindings";
import { numberToBytesLE } from "@noble/curves/abstract/utils";
import { ed25519 } from "@noble/curves/ed25519";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const FIXTURE_PATH = resolve(
  __filename,
  "..",
  "fixtures",
  "aptos_ca_transfer_v1_fixture.json",
);

// -------- Fixture deterministic inputs ----------
function dkBytesFor(mul: number, add: number): Uint8Array {
  const out = new Uint8Array(32);
  for (let i = 0; i < 32; i += 1) out[i] = (i * mul + add) & 0xff;
  // Clear top nibble to guarantee the scalar is < 2^252, well below curve order.
  out[31] &= 0x0f;
  return out;
}

function fillAddr(seed: number): Uint8Array {
  const a = new Uint8Array(32);
  for (let i = 0; i < 32; i += 1) a[i] = (i + seed) & 0xff;
  return a;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

function scalarBytesLE(s: bigint): string {
  return bytesToHex(numberToBytesLE(s, 32));
}

function genListOfDeterministicScalars(count: number): bigint[] {
  // Mirrors `ed25519GenListOfRandom` (rejection-sampled mod CURVE.n, big-endian
  // bytes-to-bigint). We call it explicitly here so the randomness is consumed
  // BEFORE the SDK does, giving us blinding factors we can pass to `proveTransfer`.
  const out: bigint[] = [];
  for (let i = 0; i < count; i += 1) {
    let s: bigint;
    do {
      const buf = new Uint8Array(32);
      globalThis.crypto.getRandomValues(buf);
      let r = 0n;
      for (let j = 0; j < 32; j += 1) {
        r = (r << 8n) | BigInt(buf[j]);
      }
      s = r;
    } while (s > ed25519.CURVE.n);
    out.push(s);
  }
  return out;
}

function encryptChunks(
  chunks: bigint[],
  ekKey: ReturnType<TwistedEd25519PrivateKey["publicKey"]>,
  randomness: bigint[],
): Array<ReturnType<typeof TwistedElGamal.encryptWithPK>> {
  return chunks.map((chunk, i) =>
    TwistedElGamal.encryptWithPK(chunk, ekKey, randomness[i]),
  );
}

describe("Aptos CA transfer parity fixture", () => {
  it("generates and verifies the byte-locked transfer fixture", async () => {
    // -------- Inputs ----------
    const senderDk = new TwistedEd25519PrivateKey(dkBytesFor(7, 3));
    const senderEk = senderDk.publicKey();
    const recipientDk = new TwistedEd25519PrivateKey(dkBytesFor(11, 5));
    const recipientEk = recipientDk.publicKey();

    const senderAddress = fillAddr(1);
    const recipientAddress = fillAddr(2);
    const tokenAddress = fillAddr(3);
    const chainId = 2;

    const ell = AVAILABLE_BALANCE_CHUNK_COUNT;
    const n = TRANSFER_AMOUNT_CHUNK_COUNT;
    expect(ell).toBe(8);
    expect(n).toBe(4);

    const oldBalance = 1000n;
    const transferAmount = 100n;
    const newBalance = oldBalance - transferAmount;
    const oldBalanceChunks = ChunkedAmount.fromAmount(oldBalance).amountChunks;
    const newBalanceChunks = ChunkedAmount.fromAmount(newBalance).amountChunks;
    const transferAmountChunks =
      ChunkedAmount.createTransferAmount(transferAmount).amountChunks;

    expect(oldBalanceChunks).toHaveLength(ell);
    expect(newBalanceChunks).toHaveLength(ell);
    expect(transferAmountChunks).toHaveLength(n);
    expect(oldBalanceChunks[0]).toBe(1000n);
    expect(newBalanceChunks[0]).toBe(900n);
    expect(transferAmountChunks[0]).toBe(100n);

    // -------- PRNG-derived blinding factors ----------
    // Order matters — see DETERMINISM CONTRACT.
    const oldBalanceRandomness = genListOfDeterministicScalars(ell);
    const transferAmountRandomness = genListOfDeterministicScalars(n);
    const newBalanceRandomness = genListOfDeterministicScalars(ell);

    // -------- Ciphertexts ----------
    const oldBalanceCt = encryptChunks(
      oldBalanceChunks,
      senderEk,
      oldBalanceRandomness,
    );
    const newBalanceCt = encryptChunks(
      newBalanceChunks,
      senderEk,
      newBalanceRandomness,
    );
    const transferSenderCt = encryptChunks(
      transferAmountChunks,
      senderEk,
      transferAmountRandomness,
    );
    const transferRecipientCt = encryptChunks(
      transferAmountChunks,
      recipientEk,
      transferAmountRandomness,
    );

    const oldBalanceC = oldBalanceCt.map((ct) => ct.C);
    const oldBalanceD = oldBalanceCt.map((ct) => ct.D);
    const newBalanceC = newBalanceCt.map((ct) => ct.C);
    const newBalanceD = newBalanceCt.map((ct) => ct.D);
    const transferAmountC = transferSenderCt.map((ct) => ct.C);
    const transferAmountDSender = transferSenderCt.map((ct) => ct.D);
    const transferAmountDRecipient = transferRecipientCt.map((ct) => ct.D);

    // Sanity: sender's and recipient's transfer-amount commitments share C (same m·G + r·H).
    for (let i = 0; i < n; i += 1) {
      expect(transferSenderCt[i].C.equals(transferRecipientCt[i].C)).toBe(true);
    }

    // -------- Range proofs (WASM RNG consumed here for the first time) ----------
    const valBase = RistrettoPoint.BASE.toRawBytes();
    const randBase = H_RISTRETTO.toRawBytes();

    const rangeAmountResult = await batchRangeProof({
      v: transferAmountChunks,
      rs: transferAmountRandomness.map((r) => numberToBytesLE(r, 32)),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });
    const rangeNewBalanceResult = await batchRangeProof({
      v: newBalanceChunks,
      rs: newBalanceRandomness.map((r) => numberToBytesLE(r, 32)),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });

    // -------- Sigma proof ----------
    const sigmaProof = proveTransfer({
      dk: senderDk,
      senderAddress,
      recipientAddress,
      tokenAddress,
      chainId,
      senderEncryptionKey: senderEk,
      recipientEncryptionKey: recipientEk,
      oldBalanceC,
      oldBalanceD,
      newBalanceC,
      newBalanceD,
      newAmountChunks: newBalanceChunks,
      newRandomness: newBalanceRandomness,
      transferAmountC,
      transferAmountDSender,
      transferAmountDRecipient,
      transferAmountChunks,
      transferRandomness: transferAmountRandomness,
      hasEffectiveAuditor: false,
    });

    // Sigma proof shape: 30 commitment points, 25 response scalars
    expect(sigmaProof.commitment).toHaveLength(30);
    expect(sigmaProof.response).toHaveLength(25);
    for (const c of sigmaProof.commitment) expect(c).toHaveLength(32);
    for (const r of sigmaProof.response) expect(r).toHaveLength(32);

    // -------- Verify all three proofs ----------
    const sigmaOk = verifyTransfer({
      senderAddress,
      recipientAddress,
      tokenAddress,
      chainId,
      ekSidBytes: senderEk.toUint8Array(),
      ekRidBytes: recipientEk.toUint8Array(),
      oldBalanceC,
      oldBalanceD,
      newBalanceC,
      newBalanceD,
      transferAmountC,
      transferAmountDSender,
      transferAmountDRecipient,
      hasEffectiveAuditor: false,
      proof: sigmaProof,
    });
    expect(sigmaOk).toBe(true);

    const rangeAmountOk = await batchVerifyProof({
      proof: rangeAmountResult.proof,
      comms: transferAmountC.map((p) => p.toRawBytes()),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });
    expect(rangeAmountOk).toBe(true);

    const rangeNewBalanceOk = await batchVerifyProof({
      proof: rangeNewBalanceResult.proof,
      comms: newBalanceC.map((p) => p.toRawBytes()),
      valBase,
      randBase,
      numBits: CHUNK_BITS,
    });
    expect(rangeNewBalanceOk).toBe(true);

    // -------- Assemble fixture JSON ----------
    const fixture = {
      version: "aptos_ca_transfer_v1",
      generator: {
        sdk: "@aptos-labs/confidential-asset@1.1.1",
        bindings: "@aptos-labs/confidential-asset-bindings@1.1.1",
        bulletproofsCrate: "bulletproofs-5.0.0",
        merlinCrate: "merlin-3.0.0",
        outerTranscriptLabel: "AptosConfidentialAsset/BulletproofRangeProof",
        sigmaProtocolId: "AptosConfidentialAsset/TransferV1",
        sigmaTypeName: "0x1::sigma_protocol_transfer::Transfer",
        prngSeed: new TextDecoder().decode(PRNG_SEED),
        determinism:
          "globalThis.crypto.getRandomValues patched to SHA-256 counter-mode " +
          "keyed by prngSeed; both noble randomBytes and Aptos WASM bulletproofs " +
          "consume from this stream. Operation order is locked in the test.",
      },
      params: {
        ell,
        n,
        chunkBits: CHUNK_BITS,
        hasAuditor: false,
        numAuditors: 0,
        amount: Number(transferAmount),
        oldBalance: Number(oldBalance),
        newBalance: Number(newBalance),
      },
      witness: {
        dk: "0x" + bytesToHex(senderDk.toUint8Array()),
      },
      statement: {
        senderAddress: "0x" + bytesToHex(senderAddress),
        recipientAddress: "0x" + bytesToHex(recipientAddress),
        tokenAddress: "0x" + bytesToHex(tokenAddress),
        chainId,
        senderEk: "0x" + bytesToHex(senderEk.toUint8Array()),
        recipientEk: "0x" + bytesToHex(recipientEk.toUint8Array()),
      },
      plaintextChunks: {
        oldBalance: oldBalanceChunks.map((c) => c.toString()),
        newBalance: newBalanceChunks.map((c) => c.toString()),
        transferAmount: transferAmountChunks.map((c) => c.toString()),
      },
      randomness: {
        oldBalance: oldBalanceRandomness.map((r) => "0x" + scalarBytesLE(r)),
        transferAmount: transferAmountRandomness.map(
          (r) => "0x" + scalarBytesLE(r),
        ),
        newBalance: newBalanceRandomness.map((r) => "0x" + scalarBytesLE(r)),
      },
      ciphertexts: {
        oldBalanceC: oldBalanceC.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        oldBalanceD: oldBalanceD.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        newBalanceC: newBalanceC.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        newBalanceD: newBalanceD.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        amountC: transferAmountC.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        amountDSender: transferAmountDSender.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
        amountDRecipient: transferAmountDRecipient.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
      },
      sigmaProof: {
        commitment: sigmaProof.commitment.map((b) => "0x" + bytesToHex(b)),
        response: sigmaProof.response.map((b) => "0x" + bytesToHex(b)),
        witnessLayout: ["dk", "new_a[ell]", "new_r[ell]", "v[n]", "r[n]"],
        commitmentLayout: [
          "ek_sid * dk",
          "G*new_a[i] + H*new_r[i] for i in [ell]",
          "ek_sid * new_r[i] for i in [ell]",
          "balance equation: dk*<B,old_R> + (<B,new_a> + <B,v>)*G",
          "G*v[j] + H*r[j] for j in [n]",
          "ek_sid * r[j] for j in [n]",
          "ek_rid * r[j] for j in [n]",
        ],
      },
      rangeProofs: {
        amount: {
          numValues: n,
          numBits: CHUNK_BITS,
          proof: "0x" + bytesToHex(rangeAmountResult.proof),
          comms: rangeAmountResult.comms.map((c) => "0x" + bytesToHex(c)),
        },
        newBalance: {
          numValues: ell,
          numBits: CHUNK_BITS,
          proof: "0x" + bytesToHex(rangeNewBalanceResult.proof),
          comms: rangeNewBalanceResult.comms.map((c) => "0x" + bytesToHex(c)),
        },
      },
      // The on-chain `confidential_transfer_raw(...)` function arguments in the
      // order Aptos CA's TS SDK encodes them. The Rust side can re-derive each
      // entry from the fields above; this section is provided as a sanity
      // cross-check.
      onChainArgs: {
        new_balance_C: newBalanceC.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        new_balance_D: newBalanceD.map((p) => "0x" + bytesToHex(p.toRawBytes())),
        new_balance_A: [], // no effective auditor
        sender_amount_C: transferAmountC.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
        sender_amount_D: transferAmountDSender.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
        recipient_amount_D: transferAmountDRecipient.map(
          (p) => "0x" + bytesToHex(p.toRawBytes()),
        ),
        effective_auditor_amount_D: [],
        voluntary_auditor_eks: [],
        voluntary_auditor_amount_D: [],
        range_proof_new_balance:
          "0x" + bytesToHex(rangeNewBalanceResult.proof),
        range_proof_amount: "0x" + bytesToHex(rangeAmountResult.proof),
        sigma_commitment: sigmaProof.commitment.map(
          (b) => "0x" + bytesToHex(b),
        ),
        sigma_response: sigmaProof.response.map((b) => "0x" + bytesToHex(b)),
        memo: "0x",
      },
      prng: {
        bytesConsumedThroughSigmaProof: prngConsumed,
      },
    };

    const fixtureJson = JSON.stringify(fixture, null, 2) + "\n";

    // -------- Persist / Re-verify ----------
    const regenerate = process.env.EUNOMA_REGENERATE_FIXTURES === "1";
    if (!existsSync(FIXTURE_PATH) || regenerate) {
      writeFileSync(FIXTURE_PATH, fixtureJson);
    }
    const onDisk = readFileSync(FIXTURE_PATH, "utf8");
    expect(onDisk).toBe(fixtureJson);
  });
});
